### ISSUE TITLE
Very unfriendly compiler error

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#1000]
If a user writes this program:

```grain
let foo = ""

foo.charAt(0)
```

Nothing is reported in the LSP, and then when you go to compile the program, the compiler crashes with:

```
grainc.exe: internal error, uncaught exception:
                   (Failure "Impossible: deprecated error type in typetexp")
```

I was only able to debug this by changing the compiler to output the identifier name. How should we handle this better?

**Comment by marcusroberts** [comment]
I'll take a look at why the LSP is silent

**Comment by marcusroberts** [comment]
Oh, it will be if the compiler errors.  It should indicate there's been a problem though I think,

**Comment by ospencer** [comment]
@marcusroberts it's silent because it's an error that's not handled by the compiler.
