### ISSUE TITLE
Printing records defined in different modules prints an opaque record

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#1021]
From my chat with @ospencer

* Variants/records are created with the module's id so at runtime we can look up the type info.
* Variants are created from the file in which they're defined (because we export functions)
* Records are not which means if you create a record in a different file than which it's defined, it has the module id of that module instead of the other one

This is going be a much large fix because the fix is to refactor it completely.

_Originally posted by @phated in https://github.com/grain-lang/grain/pull/1019#discussion_r743330243_

**Comment by peblair** [comment]
Possible idea: export a per-type WASM function for each module which returns the tag information. Then, at the construction sites, we call that function to populate the tag info appropriately. @ospencer do you think that'd work?

**Comment by ospencer** [comment]
It would, but I think it complicates it a bit. The fix I want to do is assign module IDs at compile time rather than runtime. That solves quite a few problems and gets us closer to using a universal wasm linker instead of our custom one.
