### ISSUE TITLE
Add a String.reverse() function

### ISSUE THREAD

**Issue by technosophos** [grain-lang/grain#1022]
In the spirit of adding `reverse()` functions in places where they usually show up in standard libraries, a `String.reverse()` would be a nice addition.

The desired behavior would be something like:

```
assert String.reverse("olleH") == "Hello"
```

**Comment by technosophos** [comment]
I am working on a PR for this (assuming it's something y'all would like).

**Comment by phated** [comment]
Sounds good! Thanks 🎉
