### ISSUE TITLE
List Pattern-matching abnormalities

### ISSUE THREAD

**Issue by timgestson** [grain-lang/grain#1023]
In the below example, the tokenizeBoolean1 will succeed and the tokenizeBoolean2 will fail based purely on the ordering of the match statements
```
let tokenizeBoolean1 = charlist => {
    match (charlist) {
      ['f', 'a', 'l', 's', 'e', ...rest] => false,
      ['t', 'r', 'u', 'e', ...rest] => true,
      _ => fail "Illegal Boolean",
    }
}
let tokenizeBoolean2 = charlist => {
    match (charlist) {
      ['t', 'r', 'u', 'e', ...rest] => true,
      ['f', 'a', 'l', 's', 'e', ...rest] => false,
      _ => fail "Illegal Boolean",
    }
}


print(tokenizeBoolean1(['f','a','l','s','e','m','o','r','e']))
print(tokenizeBoolean2(['f','a','l','s','e','m','o','r','e']))
```

**Comment by peblair** [comment]
Interesting. I thought this was an issue with how constant-valued patterns are compiled, but it appears to be worse than that. This program reproduces the issue as well.
```
let tokenizeBoolean1 = charlist => {
  match (charlist) {
    [f, a, l, s, e, ...rest] when f == 'f' && a == 'a' && l == 'l' &&
    s == 's' &&
    e == 'e' => false,
    [t, r, u, e, ...rest] when t == 't' && r == 'r' && u == 'u' && e == 'e' =>
      true,
    _ => fail "Illegal Boolean",
  }
}
let tokenizeBoolean2 = charlist => {
  match (charlist) {
    [t, r, u, e, ...rest] when t == 't' && r == 'r' && u == 'u' && e == 'e' =>
      true,
    [f, a, l, s, e, ...rest] when f == 'f' && a == 'a' && l == 'l' &&
    s == 's' &&
    e == 'e' => false,
    _ => fail "Illegal Boolean",
  }
}

print(tokenizeBoolean1(['f', 'a', 'l', 's', 'e', 'm', 'o', 'r', 'e']))
print(tokenizeBoolean2(['f', 'a', 'l', 's', 'e', 'm', 'o', 'r', 'e']))
```

**Comment by ospencer** [comment]
I was looking at this earlier today actually. It looks like we're losing some branches that would never match unless a preceding branch had a guard. This doesn't appear to be the case if the two structures share the exact same shape.

**Comment by peblair** [comment]
@ospencer I'm a little confused. The program I put _does_ have a guard, so why is the problem reproduced? Maybe I'm misunderstanding what you're saying.

**Comment by ospencer** [comment]
Sorry, my sentence was phrased weird.

```
match ([1, 2, 3]) {
  [a, b, ...rest] when false => ...,
  [a, b, c, ...rest] => ...
}
```

In this example, if the first branch didn't have a guard, the second branch would never match, since the first one would always take that case. So I think we're dropping that second branch since we think it could never be matched (we're not respecting that the first branch doesn't actually always match everything the next branch does).
