### ISSUE TITLE
Calling a function with an external program such as JS results in an error or error message

### ISSUE THREAD

**Issue by cekongnet** [grain-lang/grain#1028]
compile such code with --use-start-section
export let inc=(x)=>{
    x+1
}
calling inc() function with js or external program results an incorrect value
call inc(1),get 3;call inc(2),get error

**Comment by ospencer** [comment]
Hey @cekongnet, this occurs because no translation occurs between the Grain value and JavaScript value. 

We'll have a solution that can generate proper bindings to JS in the near future.

**Comment by ospencer** [comment]
If you want some guidance on how to implement the bindings manually, please reach out on Discord.
