### ISSUE TITLE
Use exceptions in the `Err` case of `Number.parseInt`

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#1057]
Right now the errors are just plain strings. It'd be more useful if they were exceptions we could pattern match on.

Blocked on #1053

**Comment by phated** [comment]
This is unblocked because `Result` is available as a language-supplied type now.

**Comment by spotandjake** [comment]
This has been blocked by #1755 or #1759 either one would allow this to move forward.

A decision was made to use enums in the case of exceptions the reason this is blocked is because you cannot re-export the enum to get this working properly.

**Comment by spotandjake** [comment]
We are going to switch this back to using an enum instead of an exception which means this is blocked on #1886
