### ISSUE TITLE
Bad range with import foreign

### ISSUE THREAD

**Issue by jtenner** [grain-lang/grain#1062]
Problem replication:

```rs
import foreign wasm to_string: (WasmI64, WasmI32) -> void from "lunatic::error"
```

Looks like it reports `(WasmI64, WasmI32` as the range, when the problem is the `Void` keyword.

**Comment by ospencer** [comment]
This one's going to be a really hard fix as-is, but it won't be a problem in 0.5. That'll be out in roughly a month's time.
