### ISSUE TITLE
String.slice and Buffer.addStringSlice have different API signatures

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#1071]
Edited: Original description had flipped functions

While working on #1065, it was uncovered that the API signatures of these are different, `Buffer.addStringSlice` takes `start` and `length` while `String.slice` takes `start` and `end`. This is a problem because `Buffer.addStringSlice` uses `String.slice` underneath and we needed to apply a workaround to find the ~~length~~ end based on length..

We want to align these APIs, but that is a breaking change that we need to batch for our next breaking release.

**Comment by peblair** [comment]
@grain-lang/core My vote is to make `String.slice` take a `start` and `end` value, since that aligns with Python (`str[start_idx:end_idx]`), [Java](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#substring(int,%20int)), and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice). Other people's thoughts?

**Comment by cician** [comment]
My take on this is that the important thing is for the two of them to match.

I don't really like reasoning with start+end compared to start+len and I almost never get it right at the first attempt with offset by one errors. But it does feel familiar coming from Java. So 👍 anyway.

I'd support adding something like `sliceLen(start,length)` to both Buffer and String, in addition to `slice(start,end)`.

**Comment by phated** [comment]
It seems that I swapped the functions in the original description. I'll edit that now.

So, `String.slice` already takes `start` and `end` and they also have "negative wrap around". I think we should change `Buffer.addStringSlice` to take `start` and `end` instead of `length`.

**Comment by cician** [comment]
I also wanted to add a `toStringSlice` function to the Bytes module, but I'm waiting for a consensus on this to make it consistent with the rest.
