### ISSUE TITLE
Unable to run Grain binary on Linux

### ISSUE THREAD

**Issue by ayaka14732** [grain-lang/grain#1078]
I download the latest [v0.4.5](https://github.com/grain-lang/grain/releases/download/grain-v0.4.5/grain-linux-x64) binary following [the official tutorial](https://grain-lang.org/docs/getting_grain). However, when I run `grain hello.gr` it shows an error:

```
Pkg: Error reading from file.
```

**Comment by cician** [comment]
HI!

Could you run `which grain` on the command line and paste the input?

If you want, feel free to hop in on Grain's support channel on discord (https://discord.com/invite/grain-lang).

**Comment by ayaka14732** [comment]
```sh
$ grain
Pkg: Error reading from file.
$ which grain
/usr/bin/grain
```

**Comment by cician** [comment]
I think it's a different binary. If you followed the instructions to the letter, then the binary is at `/usr/local/bin/grain`.

Try running `/usr/local/bin/grain hello.gr`. If this works then we can investigate what the other binary is.

**Comment by ayaka14732** [comment]
Sorry, it turns out that this is my fault. Thank you!

**Comment by ospencer** [comment]
Thanks for debugging @cician!

**Comment by cician** [comment]
You welcome / どう致しまして. I'm a bit curious what the other binary is.

**Comment by ayaka14732** [comment]
@cician Thank you! It was because I am using Arch Linux, I need to write a `PKGBUILD` script and use `makepkg` to install it into the system directory (`/usr/bin`). However, I did not realise that `makepkg` will strip the executable by default, which corrupts the file. I figured it out after I found that ``diff `which grain` ./grain`` reported the two binary files were different.
