### ISSUE TITLE
Grainfmt: lambda args are pushed into the expression

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#1091]
`let testfn = String.forEachCodePoint(c /* arg*/ => {
  // a
  void
}, "")`

the /* arg*/ ends up in the block

`let testfn = String.forEachCodePoint(c => { /* arg*/
  // a
  void
}, "")`

github code formatting doesn't show the line breaks

**Comment by phated** [comment]
@marcusroberts does this only happen *after* we remove the parens around the parameter? If so, can you leave/add the parens if there's a comment?

**Comment by marcusroberts** [comment]
The problem is deeper - it's because we use Doc.lineSuffix to push comments after separators like commas so we don't end up with  

item // comment ,
item

so we need extra logic to handle when it's followed by a block
