### ISSUE TITLE
Compiler: caching of CMI files seems to refresh on every source file change

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#1094]
With a single source Grain file, on first compile it compiles all dependencies.  The next recompile is quick as it uses the cached dependencies and in verbose mode reports compiling only the specified source file.

If I make a change to the source file, the next compile rebuilds all dependencies.

May be related to changed made in https://github.com/grain-lang/grain/pull/1061

**Comment by phated** [comment]
@marcusroberts has this been confirmed to be tied to the `--lsp` flag to grainc? Can you update this to be specific about that?

**Comment by marcusroberts** [comment]
Yes, this is related to the lsp flag.  The current LSP invokes the compiler and specified lsp mode with the --lsp flag to just generate warnings and errors, and of course regular compiles don't do this, so a flag change is detected and everything is recompiled.

We could fix it by telling the lsp flag to be ignored, but this will be fixed in the next lsp version where it's a separate binary (that runs as a server process)
