### ISSUE TITLE
Graindoc: Preserve indentation during line trimming

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#1096]
As discussed on last discord meeting, markdown quoted blocks don't preserve spaces at beginning of lines. Which makes it impossible to indent inline examples.

For example this
```
/**
 * ```grain
 * JSONObject([
 *   ("currency", JSONString("€")),
 *   ("price", JSONNumber(99.99)),
 * ])
 * ```
 */
export enum JSON {
  ...
}
```

results in
```grain
JSONObject([
("currency", JSONString("€")),
("price", JSONNumber(99.99)),
])
```

**Comment by phated** [comment]
I'm going to adjust this title a little bit because we should just preserve indent on all graindoc
