### ISSUE TITLE
Grain Should be Versioned

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#11]
The Grain compiler should be versioned, so the runtime can be deployed with each version.

**Comment by belph** [comment]
Related: The Grain ABI is versioned at this point. We should likely start enforcing ABI compatibility within the runtime.

**Comment by ospencer** [comment]
Fixed by #154

**Comment by phated** [comment]
@ospencer not quite, I actually have a fix for grainc in a branch. Was waiting for Reason to land before submitting it

**Comment by belph** [comment]
Yeah, this is a separate issue, I believe. Reopening so we can discuss.

**Comment by ospencer** [comment]
@phated is this all set?

**Comment by phated** [comment]
@ospencer my thing was fixed, but I don't think "We should likely start enforcing ABI compatibility within the runtime." is done yet. However, I think this issue is vague enough that we could close it out and open more detailed versions of the remaining parts.

**Comment by ospencer** [comment]
Sounds good.
