### ISSUE TITLE
Compiler: Ast_helper locations should not be optional

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#1106]
It's too easy to accidentally forget to pass locations to parsetree nodes because they're optional.

(They're currently optional to make writing tests a little easier, but we no longer feel it's worth it.)

**Comment by tyrone-wu** [comment]
I can take this up if no one is working on this? ʕ•́ᴥ•̀ʔっ

**Comment by ospencer** [comment]
Go for it!
