### ISSUE TITLE
Graindoc: Add required --current-version flag instead of using grain version

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#1110]
When comparing the `@since` attribute in graindoc, we currently use the version of grain itself to display `next` on newer versions. This doesn't work for external libraries, nor does it work for Grain itself (our docs are always 1 version behind).

We need to add a required `--current-version` flag that sets the version to compare. This is a breaking change since it is adding a required flag.

**Comment by ospencer** [comment]
Any chance this flag can be optional? I really like that users can just run `grain doc file.gr` and get something really useful out of it.

**Comment by phated** [comment]
Can't be optional if you are using since. I can delay throwing until then, though.

**Comment by ospencer** [comment]
That works!
