### ISSUE TITLE
Remove --experimental-wasm-bigint flag when wasm-bigint is no longer experimental

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#114]
Once this feature in Node.js is no longer experimental, we can remove this flag.

https://github.com/grain-lang/grain/blob/master/cli/bin/grain.js#L2

**Comment by phated** [comment]
Just ran into this. We need to specify an engine because I was using node 10 LTS and it failed

**Comment by ospencer** [comment]
Made #120 to address. I'll probably get around to it tomorrow.

**Comment by ospencer** [comment]
Node 16 becomes LTS on October 26. I think that's when we should drop support for Node 14 🙂

**Comment by phated** [comment]
Since that's a breaking change, I don't expect it to happen until our next minor release, which I'm also not expecting to happen in 1.5 months 😛 But, likely in Grain 0.5, yeah.
