### ISSUE TITLE
Add smoketest for runtimes with limited features

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#1160]
We currently use the multivalue feature of Binaryen to manipulate the wasm stack via tuples, but don't utilize any multivalue functions. Because the flag for multivalue is turned on, Binaryen _may_ perform an optimization that would introduce a multivalue function/type. This test would verify that this doesn't occur using a runtime that doesn't support multivalue, like Node 14 or the NEAR runner.

**Comment by phated** [comment]
My thoughts here are that we should use https://github.com/near/workspaces-js to write a "test" for a simple "hello world" grain program. I believe we can get by with the `SandboxWorker` version as long as we are running on linux CI.

**Comment by phated** [comment]
Here is an example contract: https://github.com/grain-lang/near-simple-counter
