### ISSUE TITLE
Compiler crashes on out of date generated wasm when updating the compiler

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#1203]
Crash log 

PS C:\Users\marcus\Grain\grain> grain .\hello.gr
C:\Users\marcus\Grain\grain\cli\bin\grainc.exe: internal error, uncaught exception:
                                                Invalid_argument("Types.val_repr")
                                                Raised at Grain_typed__Cmi_format.deserialize_cmi in file "src/typed/cmi_format.re", line 102, characters 23-49
                                                Called from Grain_utils__Wasm_utils.BinarySection.load.process in file "src/utils/wasm_utils.re", line 464, characters 17-40
                                                Called from Grain_utils__Wasm_utils.BinarySection.load in file "src/utils/wasm_utils.re", line 472, characters 14-31
                                                Called from Grain_typed__Cmi_format.read_cmi in file "src/typed/cmi_format.re", line 124, characters 9-36
                                                Called from Grain_typed__Module_resolution.read_file_cmi in file "src/typed/module_resolution.re", line 46, characters 14-36
                                                Called from Grain_typed__Module_resolution.Dependency_graph.get_dependencies in file "src/typed/module_resolution.re", line 318, characters 17-41

**Comment by ospencer** [comment]
Fixed in #1314
