### ISSUE TITLE
AST: List locations aren't reported correctly

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#1221]
Because of the syntactic sugar for lists, we don't get the locations of items inside lists reported properly.     Usually we get the dummy location.

This impacts the LSP as it can't get the true location for list items to determine where the cursor is hovering, so will return the whole list.

You'll see this when hovering over match branches where the condition and body are lists.

**Comment by ospencer** [comment]
@marcusroberts Does #1387 close this?

**Comment by marcusroberts** [comment]
Yes it does!
