### ISSUE TITLE
Implement Array.mapi and List.mapi

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#124]
After the docs were written ([you can check them out here](https://grain-lang.org/docs/stdlib/array)) it made it obvious that these functions were missing.

These functions should be similar to `Array.map` and `List.map`, but should also pass the index of each element to the map function.

**Comment by designsbysm** [comment]
Should List also have a .mapi function?

**Comment by ospencer** [comment]
Absolutely. I thought it was being implemented as a part of #94, but it's not listed there.

**Comment by ospencer** [comment]
Updated!

**Comment by designsbysm** [comment]
I'd like to tackle this, as well as #94 and #125.

**Comment by ospencer** [comment]
#94 is currently being worked on by @JacobGinsparg (I'll mention that on that issue) but I can make a new issue for the array methods you can take!

**Comment by phated** [comment]
This has been both implement AND documented! Going to close this issue. Thanks for the work @designsbysm!
