### ISSUE TITLE
Implement Array.sort and List.sort

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#125]
These functions should take the array/list and a comparator function as arguments and produce a sorted array/list.

Open questions:
- should the array version be a sort in place?
- should there be two array versions, a `sort` and `sort!` where the latter sorts in place?

**Comment by designsbysm** [comment]
Can you explain the difference use/behavior/result for sort, sortBy, and sort!? Doesn't sort in place go against functional programming practices due the side effect?

**Comment by ospencer** [comment]
`sort` and `sortBy` would be the same; I mistakenly put `sortBy` in the list issue. 

I agree that sorting in place doesn't seem like a particularly functional thing, but it's more of a case of practicality than being purely functional. OCaml Array sort, for example, sorts in place. I think that most of the time what people really want is to sort in place—it's much faster and more memory efficient than copying the array and producing a sorted version. 

That's sort of why I'm a fan of having two versions—`sort` and `sort!`, where `sort` produces a new, sorted array, and `sort!` sorts in place. This is what Ruby does, and it's nice to see at a glance if a function will modify the input.

That said, I just don't know how useful a version of `sort` that produces a new array would be, and if it's worth confusing people with two different `sort` methods.

**Comment by ospencer** [comment]
What I think we should go with is this:

For lists, `sort` takes a comparator (`(a, a) -> Number`) and a list `List<a>`. `List.sort` produces a new list (`List<a>`), ordered according to the comparator. This should be implemented via merge sort.

For arrays, `sort` takes takes a comparator (`(a, a) -> Number`) and an array `Array<a>`. `sort` sorts the array in place, ordered according to the comparator. This method should return `Void`. This should be implemented via quicksort.

How does that sound?

**Comment by designsbysm** [comment]
That's what I was thinking. But as an experiment I'd like to implement both algorithms and run some benchmarks once the initial implementation is complete.

We'll need `List.sub(start, length, list)` and `List.merge(comparator, list)` functions for the merge sort, and would make sense for Array as well.

**Comment by ospencer** [comment]
That works for me!

**Comment by tmphey** [comment]
Hey guys! I would like to try to implement this feature. Can please someone point me where to start? 
Thanks!

**Comment by ospencer** [comment]
Definitely, though I'd want to check in with @designsbysm first. Were you able to make any progress on this?

**Comment by ospencer** [comment]
@tmphey If you're interested in working on something else in the meanwhile, let me know! We're a bit behind on opening issues 😅

**Comment by tmphey** [comment]
@ospencer Sure! Let me know if there is a better thing to start with :)

**Comment by tmphey** [comment]
@ospencer As of the progress, I have `List.take` and `List.takeWhile` (as companions to existing `List.drop` and `List.dropWhile`). And I got `List.sub(start, length, list)` implement with help of take and drop functions but not sure if that's the right solution

**Comment by designsbysm** [comment]
Unfortunately, I have not made any progress. I’ve been dealing with one mess after the other at work.

 
 
 
 
 

 
    Scott A. Matthews
    designsbysm.com

    602.538.1318

**Comment by ospencer** [comment]
Hey @tmphey! I know it's been awhile 😛

Are you still interested in taking this on? If not, no worries, but I thought I should offer it up!
