### ISSUE TITLE
Grainformat: Extra newlines between comments

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#1310]
When two comments come after one another, grainformat will add extra newlines between them. This is a problem because it breaks graindoc.

Here's an example:

```grain
/**
 * Some graindoc documentation
 *
 * @param foo: bar
 * @returns foo
 */
// TODO: We need to do something
let baz = foo => foo
```

In the above example, formatting the code will insert an empty line between the graindoc comment and `// TODO` comment. Graindoc only works if it is on 1 (or 2 because of annotations)  lines before the definition.

**Comment by marcusroberts** [comment]
Confirmed it still does this, working to fix.
