### ISSUE TITLE
Same-module type alias unification issue

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#1356]
If I create a parameterized type alias and then create a weakly typed value of that type, unification does not occur:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/7244034/179210345-d483294e-b740-4c96-9269-d8885494fba9.png">

It's easy to tell here via `foo` still being reported as weak even though I used a function which should have given it a concrete type.

Interestingly enough, this does not occur for enums:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/7244034/179210170-95806c68-d1fd-40e3-9e65-51bf6c0582bb.png">

Even more interesting, this doesn't occur and the types are correct if the type/functions are declared in another module:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/7244034/179210583-f18476b0-6fad-4314-acc1-d902cea65b1e.png">

**Comment by ospencer** [comment]
It also looks like typechecking becomes completely broken and the annotation is ignored entirely if you try to resolve types that way (`Int32` != `String`):

<img width="444" alt="image" src="https://user-images.githubusercontent.com/7244034/179211487-7dae6ce7-8ea1-48df-9496-2b6b97cff4d1.png">

**Comment by EduardoRFS** [comment]
@ospencer it makes sense, Foo is not injective. Foo<String> = Foo<Int32> that doesn't mean Int32 = String.

On the second case there is nothing to expand Foo too, the bug is actually the second case.

**Comment by ospencer** [comment]
@EduardoRFS Yeah, that makes sense, and it works in the cases you'd _actually_ want to use this. I'll close this issue, but we'll open another one to look into enhanced value restriction.

cc @phated 😄
