### ISSUE TITLE
Grainfmt: Formatting causes math operations to change

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1374]
I have format on save enabled on the grain extension and when i was trying to run tests for #1373 the formatter was reformatting the test files in a way that caused the tests to fail.

![image](https://user-images.githubusercontent.com/40705786/181132766-359ec66f-26fc-4692-9d6b-d2d01cb8e2fd.png)
The above image shows the tests running fine when the extension is uninstalled and it cannot format.
![image](https://user-images.githubusercontent.com/40705786/181132817-70d026df-fabc-4e2d-87be-8bef647aafb8.png)
When the formater is run it makes the changes above.
![image](https://user-images.githubusercontent.com/40705786/181132854-99e0d280-3784-4d2d-8a90-e9827b5fed98.png)
which causes the tests to fail.

i think it might be because before it is formated it is treated as 4 / a fraction. and after formatting it is treated as repeated division.

**Comment by marcusroberts** [comment]
Just to capture in text

assert 4 / (2/3) == 6

is formatted to

assert 4 / 2 / 3 == 6
