### ISSUE TITLE
Formatter Throws Error On Invalid Grain Code

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1377]
![image](https://user-images.githubusercontent.com/40705786/181383069-50d7cc99-3589-4525-8f4b-82d83ede04c0.png)
As can be seen in the image above the formatter is throwing an error when the grain code is invalid which can be annoying if you have something like format on save enabled and are saving at incomplete times it would make more sense if it just gave the input code back unformated or was a silent error.

**Comment by marcusroberts** [comment]
Agreed, that would be better behaviour!
