### ISSUE TITLE
GrainFmt: Grain Formatter Is Duplicating Comments 

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1378]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40705786/181385993-7e24e0b8-2923-4cdc-a528-f24bbc51b98e.png">
Above is an image before the formatter runs,

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40705786/181386015-08c38714-1001-4565-946e-e5f5010c61f9.png">
After the formatter runs it has decided to duplicate the comments and everytime it runs it duplicates them again

**Comment by marcusroberts** [comment]
@spotandjake  could you paste the actual source rather than an image here for me to repro the issue from please?

**Comment by spotandjake** [comment]
https://github.com/spotandjake/BriskLinker/blob/d6a4d1fc749848fb4605c09f54a971ae7b5265a7/linker/BuildFile.gr#L114 error occurs there when formatted

**Comment by spotandjake** [comment]
actually here is a much smaller reproduction ```
import List from "list"
let test = (test) => {
  // Comments
  List.forEach((i) => {
    // Comment In ForEach
    print(i)
  }, test: List<Number>)
}
``` I think It may be related to the cast being in a parameter, as it doesn't occur usually
