### ISSUE TITLE
Support tuple destructuring without surrounding parens

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#143]
```grain
let fst, snd = ...
```

should be valid syntax.

**Comment by belph** [comment]
@ospencer This leads to some weird edge cases in the grammar:
```
let {a: b, c} = ...
```
Is `b, c` a tuple, or is `c` a field on the record?
I think the requirements here need to be tailored down a bit more before we can implement.

**Comment by ospencer** [comment]
I meant just the outermost tuple `let fst, snd = ...` without any subpattern support.

Tuple destructuring within a record should continue to work the same way.

The thought process is that values in destructuring are always separated by commas: `let [a, b, c]`, `let SomeADT(a, b, c)`, `let (a, b, c)`, `let {a, b, c}`, etc., so support for dropping the parens around a tuple in a subpattern would always be ambiguous.

**Comment by phated** [comment]
Maybe it is just golang PTSD but I don't like paren-less destructuring

**Comment by ospencer** [comment]
We're not going to do this since we don't have paren-less tuple-making.
