### ISSUE TITLE
Formatter: Issue Code Formatting

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1445]
This is invalid code so it probably isnt a priority but it is still annoying when it messes up invalid code more.
 ```
if (true)
// Copy the Separator
  true
```
 gets formatted into 
```
if (true // Copy the Separator) true
```

**Comment by marcusroberts** [comment]
Thanks for reporting.   I think I've discovered a whole class of bugs like this, I'll get them fixed pronto.

**Comment by phated** [comment]
@marcusroberts are we still planning to get this done for 0.5.5?
