### ISSUE TITLE
Formatter: incorrect line splitting within square brackets

### ISSUE THREAD

**Issue by alex-snezhko** [grain-lang/grain#1461]
If I write something like this (contrived example):
```
export let getBefore = (array, index) => if (array == [>]) "nope" else array[index - 1]
```
The formatter formats it like this:
```
export let getBefore = (array, index) => if (array == [>]) "nope"
else array[index -
1]
```
For some reason it splits the `1` onto a separate line. However, the formatting behavior changes if I were to replace the square brackets on `[index - 1]` with parentheses:
```
export let getBefore = (array, index) => if (array == [>]) "nope"
else array(index - 1)
```

**Comment by marcusroberts** [comment]
Thanks, fixed with a quick PR.  I think the indentation could be better, I'll fix that as I'm working on conditional formatting at the moment
