### ISSUE TITLE
stdlib: Array.rotate rotates opposite to List.rotate

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1470]
@alex-snezhko noticed that `Array.rotate` and `List.rotate` rotate in opposite directions with. 

`Array.rotate` - Rotating to the right.
and
`List.rotate` - Rotating to the left.

While you are able to rotate the other direction by using negative indexes, The behaviour seems random from a user perspective and could cause confusion.

**Comment by alex-snezhko** [comment]
Since immutable arrays (#1477) make use of left-rotation like `List`, should `Array` be modified to rotate to the left as well?

**Comment by ospencer** [comment]
Yes. Left rotation for all.

Ruby's doc for it makes it feel really intuitive:

> Returns a [new](https://apidock.com/ruby/Array/new/class) array by rotating self so th[at](https://apidock.com/ruby/Array/at) the element at [count](https://apidock.com/ruby/Array/count) is the [first](https://apidock.com/ruby/Array/first) element of the [new](https://apidock.com/ruby/Array/new/class) array.
> If [count](https://apidock.com/ruby/Array/count) is negative then it rotates in the opposite direction, starting from the end of self where -1 is the [last](https://apidock.com/ruby/Array/last) element.
