### ISSUE TITLE
Formatter: Incorrect removal of parentheses between operators of same precedence

### ISSUE THREAD

**Issue by alex-snezhko** [grain-lang/grain#1473]
It seems that the removal of redundant parentheses as addressed by #903 does not always work correctly. For example
```
let a = (2 >> 1) << 1
```
gets formatted to
```
let a = 2 >> 1 << 1
```

The compiler interprets the formatted code right-associatively, performing `1 << 1` before `2 >> 1` giving a result of `0` rather than `2` as expected from the placement of parentheses.

**Comment by marcusroberts** [comment]
Interesting!  Thanks, I'll take a look.

**Comment by marcusroberts** [comment]
I think the problem is not taking associativity into account (obviously! :) ) for equal precedence.  I'll get this fixed up.

**Comment by marcusroberts** [comment]
After talking with @ospencer this may be a Grain bug rather than a formatter bug as the parens shouldn't be needed.

**Comment by phated** [comment]
@alex-snezhko I also was wondering if you were built on main. Oscar changed some stuff with the custom infix operators that just were released.

**Comment by phated** [comment]
@marcusroberts are we still planning to have this done for 0.5.5 (whether it is a formatter or compiler bug)
