### ISSUE TITLE
Stdlib: Reintroduce `gamma`, `factorial` functions

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1478]
Currently our trig functions in the module library such as `Number.sin`, `Number.cos` and `Number.tan` have some issues. That we should correct, we should make an attempt either fully improve the implementation for a more accurate function or create fast paths for special angles that would allow for more accuracy. Another current problem is with how we map values into the a `-pi` and `pi` range. as we dont have arbitrary precision floats we lose accuracy which makes the trig functions almost useless with bigints.

Edit Note: The original issue misidentified the problem we were running into, Upon furthur investigation there seems to be some other issues, so I hijacked this issue for that.

**Comment by phated** [comment]
I updated the title since we're removing these in #2046 until the correct fix is made.
