### ISSUE TITLE
Using foreign functions with unsigned type signatures

### ISSUE THREAD

**Issue by bhelx** [grain-lang/grain#1488]
I'm looking to use some imported foreign functions that require unsigned types. Example:

```
// the wasm function imported into "env"
extism_input_length: () -> u64

// The grain foreign import statement
import foreign wasm extism_input_length: () -> WasmI64 from "env"
```

I have a similar problem when trying to use unsigned 8bit types.

Obviously this doesn't work if the types don't line up. I understand that [unsigned types](https://github.com/grain-lang/grain/issues/1222) is still in the works, but is there a way around this currently?

**Comment by ospencer** [comment]
Hey @bhelx, this is fully supported—the numbers don't have any signedness to them. You just choose to interpret them as signed or unsigned, and there's signed and unsigned versions of operators. You can check out the Int32 and Int64 libraries.

Were you looking for help writing bindings?

**Comment by bhelx** [comment]
Thanks for the quick response!

So currently, if I compile the above, the type signature from wasm-objdump is:

```
- type[45] () -> i64
```

What the host wants to pass in is:

```
type: () -> u64
```

> the numbers don't have any signedness to them. You just choose to interpret them as signed or unsigned, and there's signed and unsigned versions of operators. You can check out the Int32 and Int64 libraries.

I see. Now that I'm looking at it, wasmtime is not complaining if i use i64 in place of u64 here. I think I know where to go from here. As long as wasmtime doesn't care whether it's signed or not I can just interpret them how I need in Grain.

> Were you looking for help writing bindings?

No, but thanks! Though I may have some more questions. I'm looking at adding Grain support to our universal plugin system so that our users can choose to write plugins in Grain. https://github.com/extism/extism

**Comment by bhelx** [comment]
Going to close for the time being

**Comment by ospencer** [comment]
No worries! If extism has a component model / interface types compatible interface, let me know as I can generate the bindings. We're still working to get it fully tested and published but it's largely in working order.

**Comment by bhelx** [comment]
We don't support the component model yet, but it is something we plan to support in the future. For the time being, we basically have our own ABI. We've done this a few times so we shouldn't have too much trouble building it in Grain. I just joined the Discord so I'll be sure to share our progress there.

> We're still working to get it fully tested and published but it's largely in working order.

Is this public somewhere? Curious to see.

**Comment by ospencer** [comment]
Awesome. The hardest part is lifting/lowering types, as Grain is geared towards high level programming. A good example of some bindings might be bindings to Lunatic: https://github.com/grain-lang/lunatic-gr/tree/oscar/process

And docs around how data is laid out in memory: https://github.com/grain-lang/grain/blob/main/docs/contributor/data_representations.md and https://github.com/grain-lang/grain/blob/main/docs/contributor/low_level_programming.md

Happy to help if you run into any trouble! Feel free to ping me directly or in the #support channel 🙂 

And yes, the bindgen is public here: https://github.com/ospencer/witx-bindgen/tree/oscar/grain-bindgen

**Comment by bhelx** [comment]
Much appreciated, thank you!
