### ISSUE TITLE
Anonymous inline records for enum variants

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#1545]
It'd be sweet to be able to name the parameters for enum variants, like so:

```
enum Foo {
  Bar{str: String, num: Number}
}

let bar = Bar{str: "hi", num: 5}
```

**Comment by alex-snezhko** [comment]
As a logistical question: do you think that getting a reference to the inner record should be allowed? For example in OCaml you could do:
```
match x with
| Bar r -> ...
```
In which case `r` would be of type `Foo.Bar` and then `r.str` would be possible for instance. Should something like this be allowed in Grain? And if so, what would the syntax for that look like? Not having parentheses here complicates things a bit -- something like `Bar { ...r }` is one possible idea although it's not perfect.

**Comment by phated** [comment]
This is tough without the parens 🤔 I like the syntax you proposed but I think it'd have to be `Bar{ ...r }` to avoid parsing issues colliding with blocks (uncertain). How would something like `Bar{ foo, ...r }` work? Because `r` will still have the `foo` field, which seems confusing to folks coming from JS or other languages.

**Comment by ospencer** [comment]
The Grain syntax would be same:
```
match (x) {
  Bar r => ...
}
```
Matching on the fields would be
```
match (x) {
  Bar { str } => ...
}
```
so you're just replacing the record with the binding. Was it maybe confusing that I didn't have a space between the constructor name and the record? Spaces are allowed there.

I have mixed feelings about supporting it though. It's convenient to be able to access the record values that way, but I feel like it breaks folks' mental models of how typing in Grain works, because the record is truly attached to the constructor name `Bar`.

In OCaml if you can do
```
match x with
| Bar r -> r.str
```
(to me anyway) it makes it seem intuitive that you can do
```
match x with
| Bar r -> r
```
but that's not allowed. OCaml gives you a reasonable error, but I'm not a huge fan.

I mostly think about using inline record types to make the code more clear, but I guess another use case _is_ having lots of values, where yeah you'd really want to be able to just use the record casually instead of having to list out all of the fields.

I guess I'd be fine to support it. Curious to hear if any folks have thoughts.

**Comment by alex-snezhko** [comment]
Yeah I agree that not being able to do `Bar r -> r` in OCaml feels a bit unintuitive as you sort of conceptualize `r` as being a normal record; an alternative approach would be to have the compiler create a new type automatically but that gets into eyebrow-raising territory very quickly.

And hmm, I wasn't expecting the `Bar r => ...` syntax in Grain, it feels a bit at odds with other syntax in my opinion; for example that would also lead me to believe that if you had
```
enum Foo {
  Baz(Number, Number)
}
// then this would be possible
let foo = Baz(1, 2)
match (foo) {
  Baz a => // a is (1, 2)
}
```

**Comment by ospencer** [comment]
Heh yeah, same problem in OCaml. If we wanted to do this, it's only allowed for records (which is what OCaml does). Gets really confusing really fast!

That really leads me to believe that if you need to be able to have that functionality, you should just create a separate record type and then use it in a regular enum variant:

```
record Bar {
  ...
}
enum Foo {
  Foo(Bar)
}
match (Foo({ ... }) {
  Foo(r) => r.str // etc
}
```

**Comment by alex-snezhko** [comment]
Yeah... So should this feature of being able to grab the whole record not be implemented (at least for now)?

**Comment by ospencer** [comment]
Yeah, let's hold off for now!

**Comment by alex-snezhko** [comment]
What should the internal representation for inline records look like? Some possible approaches:
- Create an ADT with arity=1 and the first element being a pointer to the record (with the type tag being set to some dummy value).
- Keep the bit layout the same, but in the case of record ADTs just interpret the "arity" as "length" as in a record and then put the record elements afterward.
- Modify the ADT representation, adding a flag for indicating whether the ADT is a record or a tuple/singleton ADT, then interpret "arity" as "record length" if the flag is true. This makes the "record-ness" explicitly clear to a consumer of the wasm module but requires a breaking change in the bit layout.

**Comment by ospencer** [comment]
Would just keep it the same, leaning into the idea that records are just tuples with names.
