### ISSUE TITLE
Random Docs should list ranges.

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1698]
The random docs do not state a range for each function.
![image](https://user-images.githubusercontent.com/40705786/220772531-b730042a-816b-4895-95f9-572eb67c0c74.png)
It would be helpful if ranges were added for example in the description of the `nextInt32` it would make sense to note the range given it could be from `0 to 2^32-1` or from `-2^32-1/2 to 2^32-1`.

**Comment by alex-snezhko** [comment]
No longer necessary as `Random` now operates on unsigned ints
