### ISSUE TITLE
Allow arrays with a length greater then i32s.

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1722]
While working on #1721, I realized that arrays are limited to length of an int32 at the moment, We should instead allow the lenght of arrays to be any grain Number.

I am going to try and take this on.

**Comment by phated** [comment]
It's not that we need to support everything in the number type (such as rationals and floats) but we should support all integers that can be stored in it

**Comment by ospencer** [comment]
So a fun thing here is that arrays _can't_ be longer than an i32—we currently target 32-bit webassembly, and so you've got 2^32 total pointers. A single element takes up 4 bytes (32 bits), so the greatest number of elements you could theoretically have in a Grain array is 2^30, which actually always fits in a simple number, even signed.

There simply aren't enough pointers to address more elements 🙂
