### ISSUE TITLE
Add List `isEmpty`

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1784]
So this might sound useless because you could just do `length(lst) == 0` but this would have an advantage in a case where you do not care about the `length` which needs to be computed by checking every element in the list and just care about if the list has contents.

TLDR: This would be a lot faster then doing `length(lst) == 0` for lists that are not empty.

Discussion: It wouldnt really speed up `array`, or `string`, or any of the other data types maybe `map`, `set` and `queue` im not quite sure how they calculate the size but it might make sense to add to those libs as well just to keep the apis the same.

**Comment by alex-snezhko** [comment]
Couldn't you just do `lst == []` for checking emptiness?

**Comment by spotandjake** [comment]
> Couldn't you just do `lst == []` for checking emptiness efficiently?

🤦 that is a really good point sometimes you overlook some really obvious stuff.
