### ISSUE TITLE
Compiler: Require extensions for local include paths

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1797]
Currently in the module system when you write an `include` we append `.gr` onto it this behaviour works well but realistically file extensions have no meaning. We should have a discusion on weather it makes sense to require the `.gr` extension, and also if it makes sense to append it automatically a counter example to why we shouldnt auto append it is to allow for future expansion such as if we wanted to allow `include "./bindings.wit"`

**Comment by phated** [comment]
I'm hijacking this issue to require that users specify an extension for local includes. That may be `.gr`, `.whatever`, etc. Currently, they will all be handled as grain files but that may change in the future.
