### ISSUE TITLE
Compiled File Extension

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#18]
Since the Grain `.wasm` files can't be run without the Grain runtime, they should probably have a more distinct default extension such as `.gr.wasm` to make them easier to distinguish from other `.wasm` files.

**Comment by ishankhare07** [comment]
What's the current status of this issue? Would be happy to take this up if no one is working on it yet.

**Comment by ospencer** [comment]
@ishankhare07 it still needs to be done. Feel free to give it a go!

**Comment by millette** [comment]
Saw your project a few days ago but haven't dug in yet, so take my opinion with a grainof salt.

I would prefer ```.gr.wasm``` since it's still a ```.wasm``` file and the toolchain would easily see it as such.

**Comment by ospencer** [comment]
Fixed in #343
