### ISSUE TITLE
Stdlib: Add `Bytes.getIntN`

### ISSUE THREAD

**Issue by spotandjake** [grain-lang/grain#1802]
Given grain numbers support bigint I am suggesting we add the ability to get an `Int` of size `N` to `bytes` and `buffer`. `N` could either be given in `bits` or `bytes` we would have to decide what we think makes the most sense, likely `bits` for a bit more control.

Things like this will help make consuming `Bytes` from different formats a bit easier.

**Comment by ospencer** [comment]
As we have a bunch of `Bytes.getIntX` functions for all of the fixed-width number types and `Bytes.slice` to get an arbitrary number of bytes, I'm going to close this.
