### ISSUE TITLE
Lang: Trailing comma in balanced-syntax data structures

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#182]
I'm working on defining some record types and just noticed that they don't support trailing commas.

Edit: As mentioned below, this should be supported in all balanced-syntax data structures:

- [x] Records
- [x] Lists
- [x] Arrays
- [x] ADT (inside the variant constructor)
- [x] Tuples

**Comment by ospencer** [comment]
We should also support trailing commas for all balanced-syntax data structures (lists, arrays, records, ADTs, tuples).

I believe we currently only support a trailing comma for single-item tuples, i.e. `(0,)`. But we may have also gotten rid of single element tuples.

**Comment by bmakuh** [comment]
Is it cool if I work on tackling this?

**Comment by ospencer** [comment]
@bmakuh Definitely! You might find this helpful: https://github.com/grain-lang/grain/blob/master/docs/contributor/compiler_walkthrough.md

And as always, reach out on Discord if you run into any trouble 🙂

**Comment by phated** [comment]
Is the last thing here the ADTs? I've updated the list in the original issue.

**Comment by ospencer** [comment]
@phated I think so, but we'll probably need a separate issue for declarations. Or we could just use this one.

**Comment by phated** [comment]
I think we can just use this issue and update the list at the top.

**Comment by bmakuh** [comment]
Yeah, I'm working on ADTs now, just running into some snags

**Comment by bmakuh** [comment]
Right now I have this working:
```
data Menu = Pizza(Topping, Dough,)
```
But this is still throwing a syntax error:
```
let item = Pizza(Peppers, WholeWheat,)
```
I cannot seem to figure out where in parser.dyp the latter is parsed.

**Comment by ospencer** [comment]
Should be here: https://github.com/grain-lang/grain/blob/746c9bdab027b145b931129592e4b312b2b61f09/compiler/src/parsing/parser.dyp#L402-L405

**Comment by bmakuh** [comment]
Wait, `Pizza` is considered a function here? 🤯

**Comment by ospencer** [comment]
I'm not sure about all functional languages, but they're not treated as functions in OCaml/Reason at least. It's kinda neat having it this way since you can do something like `List.map(Some, [1, 2, 3])` in Grain (but that doesn't work in OCaml).

**Comment by ospencer** [comment]
(And that's why it might feel kinda weird 😄 )

**Comment by bmakuh** [comment]
Wow. That's really interesting. Thanks for the explanation!
