### ISSUE TITLE
Compiler(?): Initialize an array with a size but no data

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#187]
While trying to implement `Map.toArray`, I found that it wasn't possible to initialize a sized array with no data. I ended up using `Array.fromList(Map.toList(map))` to implement this currently but that seems very under-performant.

I *think* this needs to be implemented in the compiler, but I'm not sure.

**Comment by ospencer** [comment]
The trouble with implementing this is that we can't guarantee that there won't be runtime type errors if an array is initialized without data:

```grain
let arr = Array.new(5)
3 + arr[2] # <- undefined behavior
```

We could potentially make something like `Array.__allocateUnsafe__()` for use by library authors that really need the performance of an uninitialized array. I would also recommend something like that exist separately from the Array stdlib.
