### ISSUE TITLE
Separate wasm compilation in CLI runner and add specific error message

### ISSUE THREAD

**Issue by ShalokShalom** [grain-lang/grain#1912]
`grain compiler file` actually runs fine on this, and doesn't complain. 

Running it, then, produces some of the most confusing error messages I have seen yet. 🗡️ 

![Screenshot_20230914_234856](https://github.com/grain-lang/grain/assets/6344099/c1e2a9eb-0d49-48c7-98c8-23cb29867b31)

**Comment by phated** [comment]
A grain file is not a wasm file. This is a WebAssembly error because you passed a non-wasm module to the WebAssembly constructor.

**Comment by phated** [comment]
Re-opening because I think we can split the wasm instantiation into a separate try/catch and then say something like "Invalid WebAssembly module. Make sure you are running a `.wasm` file"

**Comment by ShalokShalom** [comment]
o.O

**Comment by ShalokShalom** [comment]
Let me get this straight. You are providing me with exactly one way to run your code, and that is via wasm. The pure compilation from grain, as said, yielded no error. 

I expect this to work, just as I did. As in any other language. This sounds like the guts of the languages are exposed to the user, and that one is currently expected to understand the inner workings, just to get the info on a super simple function, and why it failed. 

Like...

**Comment by ospencer** [comment]
`grain run` is a command that runs wasm files, not Grain programs. The command that both compiles and then runs the resulting wasm from a Grain program is just the top level `grain` command, `grain test.gr`.

It's a little different than other languages because interpreted languages like JavaScript (running in node.js) don't have a compile step—you just run the JavaScript. Compiled languages typically produce an executable that you run yourself. Since we compile to WebAssembly, which can't be run natively on your machine, we also provide a utility to run wasm files.

**Comment by phated** [comment]
The `grain run` command clearly states it takes a wasm module:
```
$ grain run --help
Usage: grain run [options] <file>

run a wasm file via grain's WASI runner
```

While the `grain` command says it compiles and runs a program:

```
$ grain --help
Usage: grain [options] <file>

Compile and run Grain programs. 🌾
```

These are not the same and `grain run` can run any wasm file, not just wasm output by grain.

**Comment by ShalokShalom** [comment]
I would expect `grain run file` to run a grain file. 

Both due to the name of it, and because its like this in other languages. 
But just `grain file` compiles, seemingly successful and gives me no output: 

![Screenshot_20230915_003654](https://github.com/grain-lang/grain/assets/6344099/e9234182-cb67-40b8-ac0d-85cdb5544c5d)

I would expect the result of the multiplication to be seen. 

Thanks a lot for your help

**Comment by ShalokShalom** [comment]
I think this section in specific, and the whole --help generally, really hide the 
`grain file` option. 

![Screenshot_20230915_003844](https://github.com/grain-lang/grain/assets/6344099/38f550f6-51b5-41fa-8223-e7343db51d7e)

I would recommend a more explicit documentation of it.

**Comment by ShalokShalom** [comment]
So now you are hi jacking my issue? I came here to find help, not to become belittled for confusing documentation and left with no answer.

**Comment by phated** [comment]
The issue topic was that running a non-wasm file through the wasm runner provided a bad error message. We have a way forward to improve the error message. Ranting about tangential things can be done in Discussions.

I've locked the issue so we can properly track the problem specified.
