### ISSUE TITLE
By default, nested functions can change state of parent function and items in its scope

### ISSUE THREAD

**Issue by mahSource** [grain-lang/grain#1917]
Consider putting compilation warnings/errors in place to warn/prevent side effects from the ability of nested functions (by default) to change the state of their parent function.  Example below.
```ts
import File from "sys/file"
import String from "string"

print("-------------------------------------------------------")
let foo: Number -> Void = (x: Number) => {
  let mut x = x // shadowing
  print(
    String.concat(
      "x  (parent) from foo (local shadow of global) after called by main: ",
      toString(x)
    )
  )
  let bar = () => { // nested function without recursion
    x = 99 // nested function changes state of parent function
    print(
      String.concat(
        "x  (parent) from nested bar after bar assignement: ",
        toString(x)
      )
    )
  }
  bar()
  print(
    String.concat(
      "x  (parent) from foo after nested func bar changed parent's state: ",
      toString(x)
    )
  )
}
let mut x = 42

print(
  String.concat(
    "\nx  (global) at start of main before call to foo: ",
    toString(x)
  )
)
foo(x)
print(
  String.concat(
    "x  (global) at end of main after call foo (and foo call to nested bar): ",
    toString(x)
  )
)
```
**Output tracing state of global and parent (local) variable x**
x  (global) at start of main before call to foo: 42
x  (parent) from foo (local shadow of global) after called by main: 42
x  (parent) from nested bar after bar assignement: 99
x  (parent) from foo after nested func bar changed parent's state: 99
x  (global) at end of main after call foo (and foo call to nested bar): 42
```

**Comment by ospencer** [comment]
This is the expected behavior and how we think it should work—we don't think a warning is appropriate because we expect users to do this often.
