### ISSUE TITLE
Warn or prevent against outright prima facie function mutation

### ISSUE THREAD

**Issue by mahSource** [grain-lang/grain#1918]
Per the Grain Guide on Mutation it says value bindings are immutable without the mut binding added in.  Maybe this is true for variables, but per the code below one can declare the same function twice and it is not overloaded, i.e. it has the same number of required parameters and all types are the same.  The default behavior should be to make the function immutable and you can opt in to mutation.  This has nothing to do with parametric polymorphism, commonly referred to as “generics”.
```ts
import Number from "number"
let foo = (x: Number, y: Number) => {
  Number.pow(x, 2) + y
}
print(foo(2, 3)) // 7
let foo = (x: Number, y: Number) => {
  (Number.pow(x, 3) + y + 10)
}
print(foo(2, 3)) // 21
```

**Comment by ospencer** [comment]
There's no mutation going on here—functions in Grain are no different than any other value. What happened here is that you _shadowed_ `foo` when you bound it again. The behavior that you're suggesting is the current behavior.
