### ISSUE TITLE
Updated scoping operator syntax

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#2002]
With the changes introduced by #2001, this issue contains the new proposed syntax for the scoping operator.

# Old syntax
```
from Module use { foo, type Foo, module Foo }
from Module.Submodule use *
```

# New proposed syntax
```
use Module.{ foo, type Foo, module Foo }
use Module.Submodule.*
```

The `use` keyword moves to the front and the module name and values are separated by a dot. There are no changes to the values included within the curly braces.

**Comment by spotandjake** [comment]
I don't happen to love this new syntax, but I don't think it terrible either and I don't really have any better ideas.

**Comment by coder0107git** [comment]
I personally like the proposed syntax here and in #2001. When I discovered #1584 I expiramented a bit with it and it was just hard to use. I think the proposed syntax changes will help with those problems.
