### ISSUE TITLE
Typescript story

### ISSUE THREAD

**Issue by montogeek** [grain-lang/grain#203]
Hi!

Great project, really like project promises.

I would like to ask about TypeScript and Reason story in the project, it was started as TS or Reason?
It is there a plan to migrate away from TypeScript? I will help if that is the case.

Thanks!

**Comment by ospencer** [comment]
Hey! The project was actually started as an OCaml project and we recently switched to Reason to make development easier for our contributors. The `.ts` files you see in the repo are actually [AssemblyScript](https://www.assemblyscript.org/) files, and we use them for some of the standard library functionality. We don't plan to change that any time soon.

Does that answer your question?

**Comment by montogeek** [comment]
Yes, it does!
Glad it uses Reason :)

Thank you!
