### ISSUE TITLE
Grainfmt: Comment lost when preceding a number

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#2042]
If I write a bizzare comment like this

`print(/*a*/ 1 /*b*/)`

The first comment is lost after formatting

`print(1 /*b*/)`

This is happening because the location of the argument is wrong (says @ospencer )

**Comment by ospencer** [comment]
In particular, this issue is specific to positive numbers. The way we check for the dash of a negative number results in an incorrect location for the argument (but not the actual number itself).
