### ISSUE TITLE
Installer not Working Windows

### ISSUE THREAD

**Issue by mathstar13** [grain-lang/grain#2114]
When I run the installer for Grain, I see nothing but a console window flash open and closed in less than a second. As far as I can tell, nothing has installed as I ran `grain --version` in command prompt and I got `'grain' is not recognized as an internal or external command, operable program or batch file.`. 

I am on Windows 11, x64.

**Comment by ospencer** [comment]
Hey @mathstar13, the binary download is not an installer—it is the compiler as an executable. You can put the binary on your PATH which will make the compiler available as `grain-win-x64` unless you rename it to `grain.exe`. You can also invoke it without putting it on your PATH by invoking it as `./grain-win-x64`.

**Comment by mathstar13** [comment]
@ospencer Thank you very much. After seeing your response I went back to the docs and saw the line "The Grain toolchain (including our CLI, compiler, runtime, and standard library) is shipped as a single binary." I completely skimmed over that when I read it. Thanks for pointing that out to me.

**Comment by ospencer** [comment]
No problem!
