### ISSUE TITLE
CI: Add test phase with optimizations disabled

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#214]
Related to #213 - we should run the test suite with optimizations disabled as a separate phase of our CI. This would help us catch bugs in non-optimized codegen.

**Comment by ospencer** [comment]
This is a good idea. Note that not all programs will work without optimizations: off the top of my head that's pretty much all of the tail-call tests, and probably some of the gc/memory tests.

**Comment by phated** [comment]
Note that with #1270, you can't disable "grain optimizations" anymore (only binaryen optimizations are disabled by default and re-enabled with `--release` so this will close with that merge.
