### ISSUE TITLE
Default argument in recursive functions crashes compiler

### ISSUE THREAD

**Issue by marcusroberts** [grain-lang/grain#2151]
When I set a default value for an argument in recursive functions, the compiler crashes with

Failure("Impossible: optional argument with non-option type")

```module Main2

let rec parenthesizedExpression = () => {
  let expression1 = expression(0)
  expression1
}

and expression = (prec=0) => {  // setting the default value here causes the compiler crash
  0
}

provide let parse = (source: String) => {
  expression(0)
}

**Comment by spotandjake** [comment]
This is a really interesting error, it occurs when `Apply_too_many_arguments` is hit in `typecore.re`, interestingly if you pass the arguments as named parameters we get a different impossible error.

In grain we require arguments to be passed with their label in the defaulted case normally we have a pretty error for this but it seems something is messing it up.
