### ISSUE TITLE
CI: Refmt linting

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#218]
We need to get the autoformatting stuff figured out and add a formatting check in CI.

I'd advise against trying to format/autopromote + push in CI because it doesn't work on forks (I struggled a long time with that for gulp), but we should at least warn someone if the formatting is wrong.

**Comment by belph** [comment]
Maybe a git hook which warns on commits would be appropriate?

**Comment by phated** [comment]
Generally, I'm against commit hooks because they add significant lag to git commands.

**Comment by belph** [comment]
Valid point. I'm just trying to think of what could be the lowest-friction way to make sure it runs on everything. 🤔

**Comment by phated** [comment]
I actually have my VSCode editor set up to do "format on save", which is why some of my commits have formatting changes. OCaml LSP does a pretty great job with that.

**Comment by belph** [comment]
Totally, I think we should recommend people use that or a similar tool. We definitely need a way to run a check on code as it comes in, though, since we will be having more and more contributors as time goes on.

**Comment by phated** [comment]
Oh yeah, I already figured out how to add a linting phase to CI that will fail if code wasn't formatted

**Comment by phated** [comment]
Closing this with #220 landed. We can open another issue once we figure out how it can be improved.
