### ISSUE TITLE
Stdlib: Json

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#245]
It's super common to work with Json data, so we should provide a stdlib module for working with the data.

**Comment by pims** [comment]
This would make it very convenient to use Grain with [Wagi](https://github.com/deislabs/wagi).

**Comment by cician** [comment]
I'm working on JSON support here https://github.com/cician/grain-json. The plan is to merge it into Grain's stdlib soon.
Note this is not a very ergonomic API to use. It's meant to be used as a building block for future higher level APIs.

**Comment by phated** [comment]
Completed by #1133
