### ISSUE TITLE
Compiler: Disambiguate type imports

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#270]
Currently, there's syntactically no way to determine in this import

```grain
import { Foo } from '...'
```

if `Foo` is a type or a data constructor. The compiler understands this, but users and syntax highlighters are unable to tell the difference.

### 1. Separate type import keyword

```grain
import data { Foo } from '...'
```
or
```grain
import-data { Foo } from '...'
```

### 2. A keyword to differentiate a type value
```grain
import { data Foo } from '...'
```
or
```grain
import { type Foo } from '...'
```

### 3. Keywords for all values
```grain
import (
  data Foo
  val Bar
) from '...'
```

**Comment by ospencer** [comment]
The second option feels the best to me. I don't like the first option since it duplicates the `from` statement, and the third option feels too verbose.

**Comment by z0w0** [comment]
TypeScript does `import type { a } from './b'` https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
