### ISSUE TITLE
Compiler: Use user-defined function names in wasm output

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#273]
This would make Grain far more debuggable for both users and developers, as the function names show up in stack traces (with or without source maps) and of course in the wasm output.

Seeing the actual function name would be loads better than just `$GRAIN$LAM_55`.

Due to limitations with wasm source maps, we can't just source map to the original names.

Open questions: 
- How should shadowed functions be named?
- How should anonymous functions be named?

**Comment by phated** [comment]
@ospencer fixed this for exported functions, but not for all functions in the wasm output. There's still some work that needs to be done.

**Comment by ospencer** [comment]
This has been done, potentially by #1244 (but not clear).

**Comment by ospencer** [comment]
I'll also note that for fully linked modules, names are not expected to be retained (they don't exist in wasm binaries, which is what the linker stitches together).
