### ISSUE TITLE
Compiler: Support constant patterns in pattern matching

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#284]

**Comment by phated** [comment]
What is a constant pattern?

**Comment by ospencer** [comment]
It's being able to do like 
```
match (...) { 
  | 5 => print('five') 
  | 6 => print('six') 
  | _ => print('not five or six') 
}
```

It's sorta syntactic sugar over `| a when a = 5 => ...` (though I suppose you could implement it directly without it being sugar).
