### ISSUE TITLE
Compiler: Establish Grain's operator precedence (and ensure we match that precedence)

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#287]
We should create a table and then check it into source control. We should also probably add a section to the docs on it.

**Comment by ospencer** [comment]
And so it has been established:

| Precedence | Operator type | Associativity | Operators |
|-|-|-|-|
| 170 | Grouping | n/a | `( … )` |
| 160 | Member Access<br>Computed Member Access<br>Function Call | left-to-right<br>left-to-right<br>left-to-right | `… . …`<br>`… [ … ]`<br>`… ( … )` |
| 150 | Postfix Increment<br>Postfix Decrement | n/a | NYI |
| 140 | Logical NOT<br>Bitwise NOT<br>Unary Negation<br>Unbox<br>Prefix Increment<br>Postfix Increment<br>`assert`<br>`fail` | right-to-left | `! …`<br>NYI<br>`- …`<br>`^ …`<br>NYI<br>NYI<br>`assert …`<br>`fail …` |
| 130 | Exponentiation | right-to-left | NYI |
| 120 | Multiplication<br>Division<br>Modulus | left-to-right | `… * …`<br>`… / …`<br>`… % …` |
| 110 | Addition<br>Subtraction | left-to-right | `… + …`<br>`… - …` |
| 100 | Bitwise Shift Left<br>Bitwise Shift Right<br>Bitwise Arithmetic Shift Right | left-to-right | NYI |
| 90 | Less Than<br>Less Than or Equal To<br>Greater Than<br>Greater Than or Equal To | left-to-right | `… < …`<br>`… <= …`<br>`… > …`<br>`… >= …` |
| 80 | Structural Equality<br>Structural Inequality<br>Physical Equality<br>Physical Inequality | left-to-right | `… == …`<br>`… != …`<br>`… is …`<br>NYI |
| 70 | Bitwise AND | left-to-right | NYI |
| 60 | Bitwise XOR | left-to-right | NYI |
| 50 | Bitwise OR | left-to-right | NYI |
| 40 | Logical AND | left-to-right | `… && …` |
| 30 | Logical OR | left-to-right | `… \|\| …` |
| 20 | Ternary Conditional | right-to-left | NYI |
| 10 | Assignment | right-to-left | `… = …`<br>`… := …`<br>`… += …`<br>`… -= …`<br>`… *= …`<br>`… /= …`<br>`… %= …` |

I took inspiration from the operator precedences of C and JS.

@grain-lang/core this feels pretty solid and definitely something to work from, but let me know if I missed anything.

**Comment by phated** [comment]
Makes sense to me! As per our chat in discord, I wanted to give a shoutout for `isnt` as the Physical Inequality operator when we implement it. I like a single keyword over `is not` 😛
