### ISSUE TITLE
Compiler: Parse infix bitwise operators

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#297]
Even if they aren't defined yet, we should still parse `&`, `|`, `^` (tbd), `<<`, `>>`, and `>>>` so they can be used.

**Comment by bmakuh** [comment]
@ospencer you cool if I take this one?

**Comment by bmakuh** [comment]
Also, what's the tbd on `^`?

**Comment by ospencer** [comment]
@bmakuh Absolutely!

**Comment by ospencer** [comment]
The tbd on `^` is that we currently use it as the unboxing operator. We have `let mut` now, so it's a little less necessary that we have syntax for that operator.

Now that I think about it though, we can totally unambiguously parse when it's an infix operator versus when it's a prefix operator.

**Comment by ospencer** [comment]
If you feel like giving that a shot, definitely give it a go. It may be a little annoying depending on your experience with parser generators (and more specifically dypgen), but we could also pair on it if it gives you a headache!

**Comment by ospencer** [comment]
Here's where we keep all of the operator precedences: https://github.com/grain-lang/grain/blob/master/docs/contributor/operator_precedence.md

**Comment by bmakuh** [comment]
@ospencer sorry just finally getting around to this. For these operators, is this what you were intending?
| sigil | operator |
| --- | --- |
|`&` | AND |
| `\|` | OR |
| `^` | XOR |
| `<<` | left shift |
| `>>` | right shift |
| `>>>` | ? |

**Comment by bmakuh** [comment]
Also, do we want a NOT operator like `~`?

**Comment by ospencer** [comment]
Yup, `>>` is the arithmetic (signed) right shift operator, and `>>>` is the logical (unsigned) right shift operator.

And yeah, we don't want `~` right now since we might be using `~` for something else 🙂

**Comment by bmakuh** [comment]
Ok, thanks. And is there any danger of ambiguity between an infix bitwise pipe operator and other uses of the pipe? I guess we're not using it for `match` anymore, but it came to mind after you mentioned the unboxing operator

**Comment by ospencer** [comment]
There shouldn't be! It's only used for `||` now (and pipeline in the future).

**Comment by phated** [comment]
This was completed by #425 🎉
