### ISSUE TITLE
Grain Supports Separate Compilation

### ISSUE THREAD

**Issue by belph** [grain-lang/grain#3]
Modules in Grain are currently a bit of a hack; we essentially `#include` everything. It would be better if we could separately compile modules and link them separately. There are a few challenges here:
- How do we want to store compiled modules? Should we have a Grain object file format (`groff`?...heh)? We need the compiled code along with the module's static information (so that we can throw compile errors for things like missing functions).
- Where should the linking take place? One attractive option is having the separate compilation produce _two_ files (one with just the WASM, and one with the static info) and using [WebAssembly's native module support][wasm-modules] and just let WASM sort it out.
- Could we maybe even support linking against modules written in Javascript? We could then theoretically implement the DOM functionality in idiomatic Javascript (or, more exotically, anything we could `babel`ify appropriately) as opposed to the standard library.

[wasm-modules]: https://webassembly.github.io/spec/syntax/modules.html#exports

**Comment by ospencer** [comment]
@belph This was addressed in #20, yes?

**Comment by belph** [comment]
Obsoleted by addition of dynamically linked modules from over the summer. Go team!
