### ISSUE TITLE
Stdlib: Implement List.drop and List.dropWhile

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#310]
`List.drop` should take a number `n` and a list `l`, and return `l` with the first `n` elements removed. If `n` is greater than `List.length(l)`, return an empty list.

`List.dropWhile` takes a function instead of `n`.  The function takes one argument, an element of the list. `List.dropWhile` removes elements of the list until the given function returns `false`.

**Comment by tatchi** [comment]
Hey, I would be happy to give it a shot (if ok for you ofc)

**Comment by ospencer** [comment]
@tatchi Of course! Thanks a ton. Let us know in Discord if there's anything we can do to help out 😄

**Comment by ospencer** [comment]
Completed in #318
