### ISSUE TITLE
Refactor giant if/else in File stdlib to use pattern matching

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#337]
This is the code in question: https://github.com/grain-lang/grain/blob/4c03b34094e500fb90f7ed81f19fcfddf4c112ce/stdlib/sys/file.gr#L165-L176

Now that we've got `match` guards and matching on constants, we can finally make this a pattern match! 🎉

**Comment by cometkim** [comment]
why do we need the match guard here instead of doing support direct match to primitives?

**Comment by ospencer** [comment]
@cometkim no need for guards! This should be done by matching the primitives directly—sorry for any confusion!

**Comment by fa7ad** [comment]
Hi @ospencer, I'd like to help with this one if that's okay with everyone 😊

**Comment by ospencer** [comment]
Absolutely!
