### ISSUE TITLE
Refactor map tests to use negation (rather than == false)

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#349]
In https://github.com/grain-lang/grain/blob/master/compiler/test/stdlib/map.test.gr, the tests should `assert !thing` rather than `assert thing == false`.

**Comment by ohana54** [comment]
I'm on it, should I remove `== true` as well?

**Comment by ospencer** [comment]
Yeah, that'd be great! Thanks for taking this on too 🙂
