### ISSUE TITLE
Use gran with  existing frontend frameworks.

### ISSUE THREAD

**Issue by jorgebucaran** [grain-lang/grain#35]
Hi! Grain looks super interesting. Will it be possible to use grain with existing frontend frameworks like React or Hyperapp or will it be necessary to port/rewrite such libraries to Grain first?

Cheers!

**Comment by ospencer** [comment]
Yes, this should be possible in the future. It'll probably be similar to how TypeScript does it, where you'll have to write type annotations for the things you want to import.

You can see how it's currently done for the builtins here: https://github.com/grain-lang/grain/blob/b050f22c307c9238543110f0f2088939a9023b1d/src/grain-stdlib/pervasives.grlib#L2

It'll probably have similar syntax, something like `foreign js ...`, and you'll be able to pass references to those values to the runtime at instantiation.

I've made an issue, #39, to track this.

Thanks for the interest!

**Comment by jorgebucaran** [comment]
Thanks, @ospencer! Then we should be able to close here.
