### ISSUE TITLE
Weird behavior with maps

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#350]
Thanks, 2 notes about the implementation:
1. Removing elements inside a `forEach` caused the program to hang, I don't know if it's considered a limitation of the API or a bug that should be fixed.
2. In the tests, when I tried creating the `filterTestMap` using the following function the program hanged:
```
let makeFilterTestMap = () => {
  let map = Map.make();
  Map.set(Grain, "g", map);
  Map.set(Sheep, "s", map);
  Map.set(Brick, "b", map);
  map
}
```
Any idea why?

_Originally posted by @ohana54 in https://github.com/grain-lang/grain/pull/344#issuecomment-703132144_

**Comment by phated** [comment]
I ran into this as well when implementing map and I think it's a recursion bug. I re-implemented without some closures and it went away.
