### ISSUE TITLE
[Stdlib] Add constants for positive/negative Infinity, NaN to Float32/64, Pervasives (for Number)

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#360]
This will need to be done via primitives or `foreign wasm`, since we don't have syntax for `Infinity` or `NaN`.

**Comment by ospencer** [comment]
We have constants for these for Float32/64 but not for Number. I think I rather have syntax than add constants to `Number`/`Pervasives`.

**Comment by phated** [comment]
@ospencer are all of these completed now?

**Comment by ospencer** [comment]
Yes!
