### ISSUE TITLE
[Stdlib] Implement Array.fill and Array.fillRange

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#361]
Here's the type for `fill`:
```grain
fill : (a, Array<a>) -> Void
```

`fill` should replace every item in the array with the given argument.

And here's the type for `fillRange`:
```grain
fillRange : (a, Number, Number, Array<a>) -> Void
```

`fillRange` should replace items in the array starting from the start index up to (but not including) the end index. If negative indices are supplied, they should be treated as offsets from the end of the array.

**Comment by clovis1122** [comment]
I'll implement this one!

**Comment by ospencer** [comment]
Awesome, let us know in Discord if you need any help!
