### ISSUE TITLE
[Stdlib] Implement List.product and Array.product

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#362]
Here's the type for `List.product`:

```grain
product : (List<a>, List<b>) -> List<(a, b)>
```

`List.product` should take two lists, and return a new list of tuples of all of the combinations of elements from the two lists.

Similarly, here's the type for `Array.product`:

```grain
product : (Array<a>, Array<b>) -> Array<(a, b)>
```

**Comment by Dony477** [comment]
Hi :) can i work on this issue?

**Comment by ospencer** [comment]
Absolutely! Let us know in Discord if you need any help :)

**Comment by phated** [comment]
@ospencer sorry for being late, but I believe a lot of languages call this `zip`. Should we follow suit?
