### ISSUE TITLE
[Stdlib] Queue

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#363]
We should add a new standard library called `queue.gr`. It should be immutable. There's a neat algorithm that you can find here: https://github.com/asif31iqbal/ImmutableQueue

We should start by implementing the methods described in that project's README. For the `Stack` implementation, we should just use a `List`.

**Comment by miguelcarvalho13** [comment]
Hi! Can I work on this?

**Comment by ospencer** [comment]
Sure! There's probably going to be a bit of back and forth to get this over the line, but if you're willing to [join our Discord](https://discord.gg/7U3newJ) to chat about it, definitely!

**Comment by miguelcarvalho13** [comment]
Oh! Sure I just joined there 😄

**Comment by ospencer** [comment]
Awesome!
