### ISSUE TITLE
[Compiler] Improve numberMod implementation

### ISSUE THREAD

**Issue by MaxGraey** [grain-lang/grain#375]
Just have suggestion how you could improve `numberMod` a little.
```ts
export function numberMod(x: u32, y: u32): u32 {
  let xval = coerceInt64(x)
  let yval = coerceInt64(y)
  if (yval == 0) {
    return throwError(GRAIN_ERR_MODULO_BY_ZERO, 0, 0)
  }
  // improved part
  if ((xval ^ yval) < 0) {
    let xabs = abs(xval)
    let yabs = abs(yval)
    let mval = xabs % yabs
    let mres = yabs - mval
    return reducedInteger(mval != 0 ? (yval < 0 ? -mres : mres) : 0)
  } else {
    return reducedInteger(xval % yval)
  }
}
```
original source: https://github.com/grain-lang/grain/blob/c25b3281d22371bb46d43a3c266f157b5c6873e8/stdlib/stdlib-external/numbers.ts#L964

**Comment by ospencer** [comment]
Oh yup, that's similar to how it's implemented for int64s: https://github.com/grain-lang/grain/blob/master/stdlib/stdlib-external/int64.ts#L93

We never got around to updating this one. I love the `(xval ^ yval) < 0` part, that's really straightforward, simple, and clean.

**Comment by ospencer** [comment]
Thanks @MaxGraey!

**Comment by MaxGraey** [comment]
Yeah, alos look at this part: `return reducedInteger(mval != 0 ? (yval < 0 ? -mres : mres) : 0)` which avoid multiplication

**Comment by spotandjake** [comment]
Closing this issue as this was clompleted in #2144
