### ISSUE TITLE
[Lang] Data declaration syntax update

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#379]
# Data Declaration Syntax Update

New syntax for declaring variant types:
```
enum Foo<a> {
  Bar(String),
  Baz(List<a>, Number),
  Quux
}

export enum Foo<a> { ... }
```

New syntax for declaring record types:
```
record Foo<a> {
  bar: String,
  baz: (List<a>, Number),
  quux: Bool
}
```

New syntax for pattern matching:
```
match (foo) {
  Bar(a) => a,
  Baz([hd, ...tl], 5) => {
    ...
  },
  Quux => 'quux'
}
```

## Why we're making these changes

We want Grain to be a very straightforward language, and we realized that our `data` keyword was starting to get a little overloaded. Between defining variant types, record types, and in the future creating abstract types and type aliases, we realized that it would be better for users to have explicit keywords for these actions. This way, it's immediately clear to both new and experienced Grain users what's happening with the types when reading a Grain program. 🎉

**Comment by phated** [comment]
I love this proposal! I think it will feel natural to people coming to Grain from many other languages (Rust, TypeScript, etc).
