### ISSUE TITLE
Better building instructions

### ISSUE THREAD

**Issue by ishankhare07** [grain-lang/grain#40]
Currently the build instructions say I need the following things on my path:

-  ocaml
-  opam
-  jbuilder

`jbuilder` is a little confusing as there are many softwares out there named jbuilder like:
-  [rails/jbuilder](https://github.com/rails/jbuilder)
-  [Jbuilder IDE](https://www.embarcadero.com/jbuilder)

Now if the refered `jbuilder` is the **ruby gem**, then the docs should mention to install `ruby` too along with `ocaml` and `opam`. All in all I feel a bit more details are needed.

I'll be happy to update the README with a PR once you can confirm which packages are to be installed when talking about `jbuilder`. I am assuming its the ruby gem you're talking about.

> Correction: jbuilder refers to the `jbuilder` package to be installed from `opam`. Can we mention this in the document?

**Comment by minishrink** [comment]
You should also add that jbuilder is now named `dune` to avoid confusion, although I believe that for OCaml 4.05.0 both names are used.

**Comment by ospencer** [comment]
We now have a much simpler build process! You can check it out in the guide: https://grain-lang.org/guide/getting_grain
