### ISSUE TITLE
Publish @grain/runtime to NPM

### ISSUE THREAD

**Issue by z0w0** [grain-lang/grain#406]
As part of a Webpack loader per #45 it would be very useful to be able to depend on a Grain runtime installed by NPM. Since the runtime is written in JS and bundled using Webpack I don't see any obstacle to publishing it there. This would allow a Webpack loader to require the runtime package directly through a peer dependency rather than trying to inject it via a file directly, and also allow a user to choose the runtime version they depend on.

It might also make sense to publish the @grain/cli package to NPM, although that may be more involved due to the dependency on the compiler being built?

**Comment by ospencer** [comment]
Yup, there's nothing stopping us from publishing other than having a CI process around it. We're currently working on our release process, but I can manually publish runtimes for the current versions.

We did also want to publish the CLI, though yeah that's a bit more involved 😅

**Comment by phated** [comment]
I don't think we need to have a CI process around publishing it to npm quite yet, so a manual publish should be fine.

**Comment by phated** [comment]
Sorry for the delay on this! We've published the v0.3.0 runtime at https://www.npmjs.com/package/@grain/runtime
