### ISSUE TITLE
Comparison with adding WebAssembly as just an OCaml target

### ISSUE THREAD

**Issue by ul** [grain-lang/grain#44]
Hi folks, thanks for bringing ML family goodness to WebAssembly! I wonder why did you go on the path of creating a new language as opposed to adding WA as a target for OCaml?

**Comment by ospencer** [comment]
Hey there! Grain is definitely still a work in progress. There's quite a few things that we'd like to do differently than OCaml/Reason, mostly around the semantics and the type system. We'll have a public roadmap soon that will make this more clear.

**Comment by ul** [comment]
Nice, thank you! Going to wait for roadmap then =)
