### ISSUE TITLE
stdlib: String.split

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#446]
While digging into the Advent of Code problems, I've found that many of them need a `String.split` method (unless you tweak the input data by hand).

It looks like this needs or something like `String.indexOf` needs to be implemented in AssemblyScript to make this work.

**Comment by ospencer** [comment]
This isn't all that hard, but we definitely need to implement an _actual_ algorithm for this (which is why I haven't just casually written it 😂).

**Comment by ospencer** [comment]
Okay, plot twist. We more or less already have algorithms implemented for these things with `String.contains`, `String.slice`, etc.
