### ISSUE TITLE
Upload build artifacts to GitHub releases

### ISSUE THREAD

**Issue by cometkim** [grain-lang/grain#451]
Hello Grain!

I'm looking forward to actually use Grain in production. :grin: 

I recently tried building a Grain installer & version management script using asdf-vm.
https://github.com/cometkim/asdf-grain
But there are too many dependencies required for grain build (yarn, opam, esy and more...)

If Grain uploads the compiler binaries by architecture to GitHub releases, It is getting much easier.

And plus, If a WASM build is available, using WAPM as an installer may be an option.

**Comment by phated** [comment]
Cool! This is definitely something that we are working on, but we just landed basic support to build on Windows last week. Once we are confident the tests and everything can run on Windows, we will be publishing the CLI to npm and the github package registry!

**Comment by phated** [comment]
@cometkim We've started shipping binaries with our releases, for example: https://github.com/grain-lang/grain/releases/tag/grain-v0.3.2

These are a bundled up version of nodejs and a JS-compiled version of the compiler, so they are a bit slow, but they work!
