### ISSUE TITLE
Stdlib: Need a way to parse a string into a number

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#452]
Day 2 of Advent of Code has you parsing a string like:
```
1-3 a: abcde
1-3 b: cdefg
2-9 c: ccccccccc
```

Into a ruleset to match, with the numbers being a min-max range. I'm going to implement this as a constant pattern match right now, but we should have a way to parse a string into a number.

**Comment by phated** [comment]
@ospencer do we want to close this now that `parseInt` was added or do we want to leave open until we have `parseNumber`?

**Comment by ospencer** [comment]
I think we can close once parseFloat lands.
