### ISSUE TITLE
Stdlib: String.slice

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#453]
With `String.indexOf`, we can get the first occurrence of a value in a string. But if we need to get the next occurrence of it, we need some way of getting the chunk of the string after the first occurrence. The quickest way I think we could do that is with a String.slice

**Comment by ospencer** [comment]
We've already got `String.slice`. Was there something else you were thinking of?

**Comment by phated** [comment]
You're right! I missed that when I skimmed the stdlib file 🤦

**Comment by ospencer** [comment]
It's easier to see in the docs!
