### ISSUE TITLE
grain chat?

### ISSUE THREAD

**Issue by donpdonp** [grain-lang/grain#46]
Is there a place to chat to get assitance with grain? I have not found a room on freenode or gitter or in the readme and I think such a place would be helpful.

**Comment by DanielSokil** [comment]
Indeed a chat would be nice.

**Comment by Sparkenstein** [comment]
That'd help yeah. Telegram, Matrix are few of the good options as well

**Comment by ospencer** [comment]
There's now a chat! You can find more info in the contributing guide. https://github.com/grain-lang/grain/blob/master/CONTRIBUTING.md
