### ISSUE TITLE
[Runtime] Fold memory manager into runtime.wasm

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#463]
Introduced in #461, the malloc module is loaded separately from the rest of the runtime. It should instead be included with the runtime. There are some shared utilities between things included in runtime.wasm and are standalone that both require calls to `malloc`. It is _critically_ important that the malloc that (will) exist in runtime.wasm is the only version that is ever used—importing it directly into other modules will lead to disaster.

Some of the utilities will probably need to be rewritten to pull `malloc` from the proper place.

**Comment by phated** [comment]
This has been done ⚔️
