### ISSUE TITLE
[Optimization] Remove wrapString

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#476]
For convenience, our `toString` implementation heavily utilizes a function called `wrapString`. This function takes an AssemblyScript string and converts it into a Grain string. As part of this conversion, the string is converted from UTF-16 to UTF-8. It would be more efficient for us to simply directly allocate and hand-populate a UTF-8 Grain string object, and it would prevent us from depending on the UTF-8 encoding/decoding utilities as strongly.

**Comment by phated** [comment]
We weren't able to use AssemblyScript strings afterall, so we needed to remove this already.
