### ISSUE TITLE
Stdlib: Stack and Queue API

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#493]
When we were originally writing these modules, we were largely trying to get them working rather than finalizing the APIs. The APIs should look more like this:

### Queue
```
push: (a, Queue<a>) -> Queue<a> // formerly enqueue
peek: Queue<a> -> Option<a> // formerly `head`
pop: Queue<a> -> (Option<a>, Queue<a>) // formerly dequeue
```

### Stack
```
push: (a, Stack<a>) -> Stack<a>
peek: Stack<a> -> Option<a> // formerly `head`
pop: Stack<a> -> (Option<a>, Stack<a>)
```

**Comment by phated** [comment]
I was also looking to use these yesterday and was wondering if they should have iteration methods. Does that make sense for Queues and Stacks?

**Comment by jozanza** [comment]
Would a length/size method also be useful? 👀

**Comment by ospencer** [comment]
@phated They technically don't really "make sense" but people do like them!

**Comment by ospencer** [comment]
@jozanza Absolutely.

**Comment by ospencer** [comment]
#627

**Comment by jozanza** [comment]
Should we reopen this one?
