### ISSUE TITLE
Compiler Plugins

### ISSUE THREAD

**Issue by belph** [grain-lang/grain#5]
A fun addition to Grain would be the ability to extend the compiler via plugins (similar to [GCC's plugin API][gcc-plugins]). Users could write plugins with OCaml and the compiler could load them with [`Dynlink`][dynlink]. A nice side effect of this is that supporting a useful plugin API would force us to have a clean separation of different compiler passes.

[gcc-plugins]: https://gcc.gnu.org/onlinedocs/gccint/Plugins.html
[dynlink]: https://caml.inria.fr/pub/docs/manual-ocaml/libref/Dynlink.html

**Comment by ospencer** [comment]
At the time this was a fun idea, but I'm not certain it's something we still want to pursue. The compiler won't be written in OCaml forever, and this would add a fair bit of complexity.

[OCaml has even removed support for compiler plugins.](https://github.com/ocaml/ocaml/pull/2276)

I'll leave this open for a bit, but if no one has a strong argument for why we should pursue this, I'll close it out.
