### ISSUE TITLE
Compiler: Invalid tail call optimisation

### ISSUE THREAD

**Issue by DougBoyle** [grain-lang/grain#506]
The `Optimize_tail_calls` pass changes the behaviour of the following program:
```
let rec f = x => {
 let g = x => f(x - 1)
  if (x == 0) {x} else {f(g(x))}
}

print(f(1))
```
With all optimisations enabled, this gives a memory access out of bounds error. Rebuilding the compiler with `Optimize_tail_calls` removed from `optimization_passes`, the program prints 0 as expected. I think the `f(x - 1)` call is being tail call optimised, despite `g` not being rewritten as 2 functions.

**Comment by ospencer** [comment]
Thanks for reporting! I confirmed that this is fixed by #488, so I'll make sure that gets in with extra haste.
