### ISSUE TITLE
Any interop?

### ISSUE THREAD

**Issue by mweichert** [grain-lang/grain#507]
Hi there,

As there aren't many packages available for Grain (is there a package management yet?), I'm wondering if any C interop is available so that I can use some libraries with Grain?

Thanks.

**Comment by ospencer** [comment]
Yes, it's possible. Here's the (undocumented) syntax for using an `add` function from C (or any other wasm language):
```grain
import foreign wasm add: (Number, Number) -> Number from "path/to/wasm"
```

The caveat is that you'll need to understand the data representations of both C and Grain to write bindings between the two. There is, however, [a WebAssembly proposal](https://github.com/WebAssembly/interface-types) to make this seamless in the future. Here's the documentation of how Grain types are represented: https://github.com/grain-lang/grain/blob/master/docs/contributor/data_representations.md.

Once it's much nicer to work with, we'll have proper documentation and support for it!

Re: package management, there's some work in progress, but there's lots more to do 🙂

**Comment by ospencer** [comment]
Going to close this for now. Let us know if you have any more questions!
