### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fuzzthink** [grain-lang/grain#57]
All pages are empty except Intro and Bindings. Also, where is the language reference?

**Comment by ospencer** [comment]
As always, documentation is a work in progress. There’s a lot going on behind the scenes and a lot more effort will be put into the docs once the language is more stable. The language reference will be included on the website near the docs; it’s just not written yet.

One of the goals for the near term is to get a roadmap up so it’s easier to follow what’s getting worked on.

**Comment by mindplay-dk** [comment]
> One of the goals for the near term is to get a roadmap up

@ospencer did that ever happen? I'm curious about your plans and priorities. 🙂

**Comment by ospencer** [comment]
Still working on getting an official one up 😅 but here's a slide where I talked about it recently:

![image](https://user-images.githubusercontent.com/7244034/84681480-2abc4b80-af02-11ea-9c78-303a558973fc.png)

Here's the full set of slides: 
[Grain State of the Union 2.pdf](https://github.com/grain-lang/grain/files/4781545/Grain.State.of.the.Union.2.pdf)

If you want to chat in more depth, though, feel free to join our Discord! https://github.com/grain-lang/grain/blob/master/CONTRIBUTING.md#joining-the-discord
