### ISSUE TITLE
Garbage Collection

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#6]
Since WebAssembly doesn't allow for any sort of stack introspection, we suggest using reference counting.

**Comment by belph** [comment]
Note: for this to really be useful, we're going to need to essentially implement `malloc` on top of the WASM linear memory space.

**Comment by belph** [comment]
Update on this: the `gc` branch is now using an `asm.js` implementation of K&R C's `malloc()` for its memory allocation . Next on the to-do list is to implement a notion of GC-managed types in the runtime (so we can do the ref counts).

I'm brainstorming an API to try to make this extensible; the `gc` branch has a `ManagedType` class checked in, but it's currently unused. Note that, if we opt to have some form of `mallocTagged` function, this will have an impact on the codegen, but the exact effect is unclear.
