### ISSUE TITLE
JS Runtime: Expose grainToJSVal

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#645]
This is a utility that already exists, but it should be exposed for use by users. I imagine this as `GrainModule.toJSVal`, so you can call `module.toJSVal(value)`. Alternatively, the `module.exports` functions can just be wrapped to do this automatically, with the original exports exposed under another name.

**Comment by mweichert** [comment]
Can't wait to see this. Unfortunately, I think its a road blocker for me to adopt Grain without this in place. I just can't understand how to interop with the browser without it.

**Comment by mweichert** [comment]
Hey @ospencer congrats on the v0.4 release! Glad to see NEAR protocol support coming into fruition. I'll look forward to seeing how that continues to evolve.

I was just wondering if you had a chance to look into this issue, and if its something you think could get included in v0.5?

Thanks!

**Comment by ospencer** [comment]
Hey @mweichert, thank you, we're really excited about it! I haven't been ignoring you, just been thinking about this. We may be deprecating `grainToJSVal` in favor of tooling like https://github.com/bytecodealliance/witx-bindgen (which I'm in the process of adding Grain support to). That would allow you to generate the JS glue code (and respective Grain code) to interact with Grain modules. In the future, we may even add compiler support to generate the JS directly.

I'm not sure if you care about the technical reason, but it's largely because `toJSVal`/`toGrainVal` require Grain type information at runtime. (Think record/object fields, enum variants, etc.). That's less than ideal, since you'd have to ship all of that information to the browser along with all of the code, and `toJSVal`/`toGrainVal` can be slow since they have to query for type information.

I hope that makes sense! As an added bonus, I should have something people can start playing around with for witx-bindgen in the next few weeks, so even sooner than the next major Grain release 🙂

**Comment by ospencer** [comment]
This issue will be closed by #1585 because it's going away.

**Comment by mweichert** [comment]
@ospencer any chance you might be able to show an example of how to achieve the equivalent of using `oJSVal/toGrainVal` from the browser to interact with your WASM code? Thanks!

**Comment by ospencer** [comment]
It's not necessarily in the browser, but essentially you use low-level unsafe code to extract the values. You can see some example bindings for [Lunatic](https://github.com/grain-lang/lunatic-gr) here for the general idea. We're still working on getting support for wit-bindgen done (so you can just generate all of the code), but if you've got an interface file (or can show me the interface) I can generate some working bindings for you from my WIP branch 🙂 

Just send me a DM on the Grain Discord server!
