### ISSUE TITLE
Failed: yarn compiler build

### ISSUE THREAD

**Issue by mifwarior** [grain-lang/grain#649]
**Enviroment:**
Debian 10
Node: v14.16.1

**Step ro reproduce:**

1. git clone git://github.com/grain-lang/grain
2. cd grain
3. yarn
4. yarn compiler build

**Comment by mifwarior** [comment]
[build.log](https://github.com/grain-lang/grain/files/6444126/build.log)

**Comment by phated** [comment]
Duplicate of https://github.com/grain-lang/grain/issues/569

**Comment by phated** [comment]
This is fixed in the `main` branch and in v0.3.2 - note however that we built the vendored Binaryen with GCC 7, so nothing older will work. We don't want to support anything older than GCC 7 at the current time.
