### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by heapwolf** [grain-lang/grain#657]
```
%grain --version
Grain cli 0.3.0
Grain compiler 0.3.0
```

Compile was slow the first time. But I understand thats because there's a download happening. Some indication of what's going on would be nice. That's an aside though. When running a program that contains `print("Hello, world!")`, I get the following error...

```
%grain run index.gr
[CompileError: WebAssembly.compile(): expected magic word 00 61 73 6d, found 70 72 69 6e @+0]
```

It can however successfully run the program using `wasmr index.gr.wasm`.

**Comment by ospencer** [comment]
Hey there. That's a little odd; can you tell me what OS/version you're using?

**Comment by Ivo-Balbaert** [comment]
Doesn't grain run only works with .wasm files, like in: grain run hello.gr.**wasm**   ?

**Comment by ospencer** [comment]
Great spot @Ivo-Balbaert, yes `grain run` is only meant for .wasm files. The command to both compile and run a Grain program is `grain index.gr`.
