### ISSUE TITLE
Can't reference Map record from my own types

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#665]
I stumbled upon this error to use the Map module from Standard Library: "Missing file for module Map".

I initially thought it's just the fact that the Map record isn't exported, but I'm not sure. I tried modifying the Map module to export the record and recompiling the compiler, but I get the same error. I can reference without problems both List and other non pervasive types from the standard library like File.Stats. Creating it with Map.make() does work, but I can't use it in my own type like this:

``` Grain
import List from "list"
import Map from "map"
import Float64 from "float64"

export enum JSON {
	JSONNull,
	JSONBoolean(Bool),
	JSONNumber(Float64),
	JSONString(String),
	JSONArray(List<JSON>),
	JSONObject(Map.Map<String,JSON>)
}
```

**Comment by cician** [comment]
I've rechecked and the problem is limited specific case of an exported enum. I can use a Map just fine in a non exported enum or in a record.

**Comment by cician** [comment]
With latest version of Grain from git I get this error in more situations and my json lib doesn't compile anymore. 🙁
May be a separate issue. Anyway here's a minimal case.

bug_filenotfound.gr:
```grain
export record MyRecord {
  s: String
}
```

bug_filenotfound2.gr:
```grain
import { MyRecord } from "bug_filenotfound"
```

Running
```bash
grain bug_filenotfound2.gr
```

Gives
```
File "/home/cician/workspace/Trunk/grain/stdlib/pervasives.gr", line 1:
Error: Missing file for module bug_filenotfound
```

**Comment by ospencer** [comment]
@cician, there's a breaking change in the next release—you're now required to provide relative paths for files in your project. So in this case, you'll need to change your import statement to `import ... from "./bug_filenotfound"`. You can follow the running changelog on this PR: https://github.com/grain-lang/grain/pull/690

**Comment by ospencer** [comment]
Interestingly enough, I just tried the example from your original post and it seems to be working for me! It's possible that something else fixed this.

I did however run into some other issues while working with the map itself 🙁 
Hopefully we'll have that taken care of soon.

**Comment by cician** [comment]
The latest problem is solved by adjusting relative imports. Thank you!

The original issue is still there for me though. I've reduced the reproduction code to this:

file1.gr
```grain
export record M<a> {
  something: a,
}
```

file2.gr:
```grain
import { M } from "./file1"

export enum MyEnum {
  A,
  B(M<String>),
}
```

```
cician@ciciomp:~/workspace/playing_with_grain/grain_json/local$ grain ./file2.gr 
File "/home/cician/workspace/playing_with_grain/grain_json/local/file1.gr", line 1:
Error: Missing file for module %File1
```

Seems like it's something related to generic parameters of the record.

**Comment by ospencer** [comment]
Jotting down some of my findings for when I come back to this later:

It appears that in the case where the module name is roughly similar to the file name, it works, but otherwise it doesn't. In the case of `import Map from "map"`, when the identifier `Map` is found in the type signature, the module loader tries to resolve the file `Map`, which on a case-insensitive file system resolves to the compiled stdlib `map.gr.wasm`. (If you were to import `Mapp` instead of `Map`, it would fail.) It shouldn't be trying to do this at all—it should work the same way that regular values do.
