### ISSUE TITLE
Feature request: int8, int16, uint8, uint16, uint32, uint64

### ISSUE THREAD

**Issue by Conaclos** [grain-lang/grain#672]
Hi! Thanks for this amazing work!

In my opinion, Grain lacks some usual integer types: `int8`, `int16`, `uint8`, `uint16`, `uint32`, and `uint64`.

Some advantages to support them:
- better interop with C / Rust, and other system programming languages
- better compatibility with binary serialization formats (FlatBuffers, BARE, ...)
- possibility to express new constraints

**Comment by ospencer** [comment]
The unsigned types are more useful with operator overloading. We do want to support some sort of that in the future, maybe similar to Traits in Rust!

We do have functions for unsigned operations in the `Int32` and `Int64` libraries, but I do admit that type safety to make sure everyone on the team is using the unsigned operators would be really nice.

Thanks for the issue!

**Comment by Conaclos** [comment]
Another suggestion could be to support arbitrary bit-width signed/unsigned integers. For instance int7 could refer to a signed 7-bit integer. [Zig](https://ziglang.org/documentation/master/#Runtime-Integer-Values) supports that.

**Comment by alex-snezhko** [comment]
Any ideas for the literal syntax? Presuming that `l`/`L` are meant to stand for "long" and that 64-bit is capital L whereas 32-bit is lowercase, perhaps `123s` for 8-bit and `123S` for 16-bit ints (`s` standing for "short")?

**Comment by ospencer** [comment]
I like your suggestion @alex-snezhko!

**Comment by Conaclos** [comment]
I personally prefer the rust-like syntax: `123u8`, `123i8`, ...
This requires to use `u8` instead of `uint8`, ...

**Comment by ospencer** [comment]
The Rust syntax is decent, but we're not going to break away from the Grain syntax for this feature.

**Comment by Conaclos** [comment]
I misunderstood the comment of Alex... This makes sense!
