### ISSUE TITLE
Question: generics

### ISSUE THREAD

**Issue by Conaclos** [grain-lang/grain#673]
Hi!

Is there an official support for generic types?
How to express generic constraints?

**Comment by ospencer** [comment]
Hey @Conaclos!

Yes, absolutely:

```
enum Foo<a> {
  Bar(String, a),
  Baz(a)
}

let foo = Baz(5) // type Foo<Number>

let func = (arg: Foo<a>) => { // or Foo<String> or Foo<(Number, Char)>
  ...
}
```

We also have a small amount of docs here: https://grain-lang.org/docs/guide/data_types#Type-Variables

Does that answer your question?
