### ISSUE TITLE
Imported record field access can trigger type checker exception

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#682]
When deleting the `: MatchResult` annotation on [this line](https://github.com/grain-lang/grain/blob/regexp/compiler/test/stdlib/regex.test.gr#L14), this error is raised:
```
 λ grain git:(regexp) ✗ > grain compiler/test/stdlib/regex.test.gr
/Users/pblair/views/grain/cli/bin/grainc.exe: internal error, uncaught exception:
                                              (Failure "Impossible: deprecated error type in typetexp")
```
This is not ideal. We should either correctly unify the type information to preclude an error altogether (preferable), or, if that is not possible for some reason, provide a better error message.
cc @ospencer

**Comment by ospencer** [comment]
Fixed in #1200
