### ISSUE TITLE
Document all stdlib exports

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#702]
All functions which are `export`ed in the `stdlib` folder should have a documentation comment, including those under `stdlib/runtime`.

**Comment by spotandjake** [comment]
List of all completed and uncompleted files
+ [ ] /runtime/
  + [ ] /unsafe/
    + [ ] conv
    + [ ] errors
    + [ ] memory
    + [ ] printWasm
    + [ ] tags
    + [ ] wasmf32
    + [ ] wasmf64
    + [ ] wasmi32
    + [ ] wasmi64
  + [ ] dataStructure
    + [ ] needs generation
  + [ ] debug
  + [ ] equal
  + [ ] exception
  + [ ] gc
  + [ ] malloc
  + [ ] numbers
  + [ ] numberUtils
  + [ ] string
  + [ ] wasi
+ [x] /sys/
   + [x] file
   + [x] process
   + [x] random
   + [x] time
+ [x] array
+ [x] buffer
+ [ ] bytes
  + [ ] needs generation
+ [ ] char
  + [ ] Waiting on pr
+ [ ] exception
+ [ ] float32
+ [ ] float64
+ [ ] hash
+ [ ] int32
+ [ ] int64
+ [ ] list
+ [ ] map
+ [x] number
+ [ ] option
+ [ ] pervasives
+ [ ] queue
+ [x] range
+ [x] regex
+ [ ] result
+ [ ] set
+ [ ] stack
  + [ ] Not yet Generated
+ [ ] string
  + [ ] Waiting on pr

**Comment by phated** [comment]
Thanks to the excellent effort by @spotandjake, we now have all *exports* from stdlib documented! Nothing in `runtime/` is considered to be an export, so I don't think we need an issue open to add graindoc to it.

Still, we should try to update those files whenever we are working on them!
