### ISSUE TITLE
isNaN and isFinite utility functions for Number

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#704]
As a user I need to detect NaNs ind +/-infinite Numbers.

I think it needs to be done with functions similar to numberUtils.isNaN and isFinite already present in the runtime. These functions are only for WASM primitives and not exposed.

Should this be part of the Number module currently in the making (#687)?

**Comment by peblair** [comment]
> Should this be part of the Number module currently in the making (#687)?

It can go inside of that module, but I think it should be a separate pull request.

**Comment by cician** [comment]
Implemented with PR #729 and merged to main.
