### ISSUE TITLE
What should the behavior of `Array.zip` be on arrays of different sizes?

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#730]
Currently (#719), `Array.zip` successfully returns a zipped array if the two given arrays are of the same length, and `fail`s if they are not. Some open questions:
- Should we adopt Python's `zip` semantics (allow differing lengths, with the result only as long as the shorter of the two)?
- If not, should this be a `Result` return value instead?

**Comment by peblair** [comment]
My vote on this is that we permit arrays of different lengths, with the returned array having a length equal to the shortest argument. This is in line with `zip` in Python and Haskell.

**Comment by ospencer** [comment]
We've decided to permit arrays/lists of different lengths.
