### ISSUE TITLE
Memory leak returning objects from function

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#745]
This simple program reaches memory limit and never prints "end". The used memory peaks at 3 GiB before crashing.

Same when executed with Wasmtime or Wasmer, except for the latter the runtime allows 4 GiB so more iterations or larger string is needed.

The leak occurs as long as f() returns a heap allocated object.

``` grain
let f = () => {
  " "
}

for (let mut i=0; i<100000000; i += 1) {
  let s = f()
}

print("end")
```

**Comment by cician** [comment]
I've done a little bit of testing in hope of narrowing down on the issue.

The following program prints 2. Meaning the string returned by leaky() has a reference count of two despite being referenced only by "let s" (assuming passing it into getStrRefCnt doesn't increase the count because of `@disableGC`).

``` grain
import Memory from "runtime/unsafe/memory"
import WasmI32 from "runtime/unsafe/wasmi32"
import { tagSimpleNumber } from "runtime/dataStructures"

let leaky = () => {
  toString('c')
}

@disableGC
let getStrRefCnt = (s) => {
  // based on getRefCount from gc module, for debugging
  let _HEADER_SIZE = 8n
  let ptr = WasmI32.fromGrain(s)
  let cnt = WasmI32.load(WasmI32.sub(ptr, _HEADER_SIZE), 0n)
  tagSimpleNumber(cnt)
}

let s = leaky()
print(getStrRefCnt(s))
```


Also with the following otherwise meaningless change the result is 1 and leak doesn't occur. I don't know if it's my misunderstanding of `@disableGC` or another bug. Without `@disableGC` on `foo` the result is 2. Intuitively i would think the reference count would remain the same in both cases.
``` grain
@disableGC
let foo = (a) => a

let leaky = () => {
  foo(toString('c'))
}
```

**Comment by ospencer** [comment]
Hey @cician, I've been investigating this and that's more or less the issue. It's tad tricky though, so I don't yet have a fix 😅

**Comment by cician** [comment]
No pressure! I just want to help within my abilities.
