### ISSUE TITLE
Tests: Add tests for building and running in unlinked link mode

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#753]
During a local refactor, I renamed some values in the JS runner and found that all the tests pass. It wasn't until asking @ospencer that I found out I needed to try an example program with `--no-link` to uncover a bug.

We need to add test for unlinked mode.

**Comment by spotandjake** [comment]
I think we could probably close this issue

**Comment by ospencer** [comment]
Grain no longer supports running programs unlinked as of v0.5.
