### ISSUE TITLE
Allocating a recursive function leaks memory

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#773]
Allocating a recursive function leaks memory, even if it's never executed. This simple program stops with an OutOfMemory error. Here foo() is allocated for each run of the loop and never freed. If it doesn't call itself then there's no leak.

``` grain
for (let mut i=0; i<10000000; i += 1) {
	for (let mut j=0; j<10000000; j += 1) {
		let rec foo = () => {
			print("never executed")
			foo()
		}
		void
	}
}
```

**Comment by phated** [comment]
This was solved in https://github.com/grain-lang/grain/pull/1152
