### ISSUE TITLE
Record spread syntax

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#778]
I forget, do we have record spread syntax? `{ ...config, caseSensitive: caseSensitive }` (caseSensitive could also be punned)

_Originally posted by @phated in https://github.com/grain-lang/grain/pull/680#discussion_r667370729_

**Comment by alex-snezhko** [comment]
Would this syntax be constrained to only creating records of the same type but with some values changed (like `with` in OCaml) or could it be used to create a record of one type from another that has a subset of the fields? For example in JS you could do `{...first, ...second}` to "merge" two objects together, which can be useful.
