### ISSUE TITLE
Parse error when using a generic type parameter to annotate a function call.

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#783]
You get a parse error if you remove the parens around `Array<a>` in
```grain
let array = WasmI32.toGrain(allocateArray(length)): (Array<a>)
```

_Originally posted by @phated in https://github.com/grain-lang/grain/pull/757#r675075568_

**Comment by peblair** [comment]
@phated This program builds on `main`:
```grain
let array = [>1, 2]: Array<a>
```
Are we good to close this?

**Comment by marcusroberts** [comment]
If we are let me know so the formatter can stop adding parens.

**Comment by phated** [comment]
> Are we good to close this?

I don't remember any parser code that was changed to "fix" this. Do you?

**Comment by phated** [comment]
The plan was to change our annotation syntax to `::` instead of `:`

**Comment by ospencer** [comment]
This is still a bug, that example doesn't quite trigger it. Here's one:
```
let foo = [] : List<a>
6
```

**Comment by ospencer** [comment]
Or just 
```
[] : List<a>
6
```

Bug is this is ambiguous between statements `[]: List<a>`/`6`, and `([]: List < a) > 6`.
