### ISSUE TITLE
Memory Leak in `printWasm.gr`

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#791]
These functions all leak memory at the moment. We should do one of the following:
- Fix the memory leaks
- Document the memory leaks (possibly acceptable, as these are intended for internal debugging as far as I understand).

**Comment by ospencer** [comment]
I think we should refactor these to not use pervasives and move them into `runtime/debug` so it's clear they're for debugging (and can leak all the memory they'd like).

**Comment by ospencer** [comment]
Done with #1481
