### ISSUE TITLE
Annotated recursive functions do not compile

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#793]
This program does not compile:
```grain
let rec foo: Number -> Number = (a) => { a + 1 }
```
These program do:
```grain
let foo: Number -> Number = (a) => { a + 1 }
```
```grain
let rec foo = (a) => { a + 1 }
```
The exception is as follows:
```bash
 λ grain git:(callee-owned-values) ✗ > grain tst4.gr
/Users/pblair/views/grain/cli/bin/grainc.exe: internal error, uncaught exception:
                                              (Failure "Non-name not allowed on LHS of let rec.")
```
Some further debugging indicates that this is coming from [here](https://github.com/grain-lang/grain/blob/9386f46304ad958c29bb099570f06193911f7131/compiler/src/middle_end/linearize.re#L1345), with the culprit being a `TPatAlias` which somehow appears in the tree.

**Comment by ospencer** [comment]
Fixed in #920
