### ISSUE TITLE
Array.rotate

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#795]
Implement `Array.rotate`. Moves a number of items from the start of an array to the end. A negative number moves items from the end to the start. This operation is done in place. See Ruby's [`Array#rotate!`](https://ruby-doc.org/core-2.6.1/Array.html#method-i-rotate-21).

**Comment by ibdafna** [comment]
Going to give this a try!

**Comment by cician** [comment]
The merged implementation fails for empty arrays and only works for arrays of Number. The intention was to accept arrays of any type of elements, right?

If so, do you want me to make the adjustments?

Cheers

**Comment by cician** [comment]
I went ahead and made a PR: #1048

**Comment by phated** [comment]
This was completed between #838 and #1048
