### ISSUE TITLE
Reported compiler positions are not unicode-aware

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#799]
See this example:
![image](https://user-images.githubusercontent.com/7244034/130154348-08a508f8-2880-44f4-9ee0-ef0dabec007c.png)

The 💯 emoji is four bytes, but in reality, it's only one character.

This can probably be fixed at the lexing level. This should be fixed for everywhere unicode is allowed, currently strings, characters, and comments.

**Comment by peblair** [comment]
@ospencer Is this fixed?
![image](https://user-images.githubusercontent.com/4998607/135345134-41b05e9f-c21d-4e5e-961b-29b1e55a749d.png)
If so, can we close? I believe we still utilize byte positions, but the tooling appears to support it now (or at least better support it)?

**Comment by marcusroberts** [comment]
It seems to work OK when running through the LSP and formatter.

**Comment by ospencer** [comment]
This is still broken. That example works because there aren't any more characters on that line. You can add a few spaces or a semicolon and another statement to reproduce.

**Comment by peblair** [comment]
Understood. Thank you.
