### ISSUE TITLE
Allow function reference to `Pervasives.([...])`

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#802]
There is currently no way to reference the `[...]` function defined in Pervasives (it's a syntax error). We should fix the parser to allow this.

**Comment by phated** [comment]
I believe this is no longer a possibility since the List data type was moved inside the compiler in #1648 but @ospencer can correct me if I'm wrong.

**Comment by ospencer** [comment]
We should remove `Pervasives.cons` and `Pervasives.empty` now.
