### ISSUE TITLE
Support `@disableGC` on non-function `let`s

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#814]
`@disableGC` currently only works on function bindings. After #803, it would be useful to be able to annotate toplevel `let` and `let mut` statements with it as well and have it avoid the associated `incRef`/`decRef`s (this would avoid `initPtr` and friends in the standard library).

**Comment by phated** [comment]
In #1074, the compiler was changed to no longer GC low-level types. So this isn't an issue anymore. Generally, folks will just annotate the non-function values with `@unsafe`
