### ISSUE TITLE
Cannot use `assert` in most `@disableGC` contexts

### ISSUE THREAD

**Issue by peblair** [grain-lang/grain#815]
See title. My understanding is that we need to be able to `incRef` the `assert` wrapper generated in `pervasives.gr`, but this is currently impossible, as there is no way to get a reference to it. Using `assert` should still be possible in `--no-gc`/`--compilation-mode=runtime` files, as you can re-declare it in that file (which will generate a non-GC wrapper), but there is currently no workaround for files such as `array.gr`.

**Comment by ospencer** [comment]
Going to close this because we have `@unsafe` now which allows this to be done.
