### ISSUE TITLE
What is your plan for supporting Apple Silicon?

### ISSUE THREAD

**Issue by pouyakary** [grain-lang/grain#848]
Do you have any plan to support Apple Silicon? I tried to build grain from source but it seems to be incapable of compiling on M1 and I don't have any idea what is going wrong with the build script. Do you have any idea or plan for this?

**Comment by marcusroberts** [comment]
We most definitely do as most of us are on M1 devices ourselves, but there are a couple of blocks on supporting tools at the moment.

Grain will build fine if you use Intel emulation.  My way to do this is to take a copy of the Terminal (or iTerm or your console app of choice), then Cmd-I it for info, rename it to Terminal Rosetta (or whatever you like) and tick the Open using Rosetta box.  Then everything you run in this terminal including the Grain build will run under Rosetta. 

Let me know how you get on.

**Comment by phated** [comment]
Thanks for posting you workaround @marcusroberts!

There's 2 big problems with this:
1. We **only** ship pre-built binaryen right now. I think we have a path forward in fixing this and falling back to building from source.
2. We can't prebuild M1 binaryen in CI, so it's always going to have to be built from source (which takes 30+ minutes on non-M1 hardware)

**Comment by marcusroberts** [comment]
We also can't build binaryen on M1 native at all yet due to an OCaml problem with exceptions :(

(But it will run fine in Intel compatibility just fine)

**Comment by pouyakary** [comment]
@marcusroberts thanks a lot
