### ISSUE TITLE
Formattter introduces syntax error

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#884]
I tried the new formatter and I like it, but I found that it fails for match statements with a comment on the same line like this:
```grain
match (1) { // fails
    1 => "1",
	_ => "*"
  }
```

The resulting code:
```grain
match (1 // fails) {
  1 => "1",
  _ => "*",
}
```

Cheers.

**Comment by marcusroberts** [comment]
Thanks for reporting this, that's a case I didn't think of.  I'll get a fix out soon.
