### ISSUE TITLE
Printing a list returned by `List.reverse` seems to be incorrect.

### ISSUE THREAD

**Issue by Ultra-Instinct-05** [grain-lang/grain#892]
## Problem description

Printing a list returned by `List.reverse` seems incorrect.

## Steps to reproduce

1. Save the following code in a file e.g. `test.gr`.
```
import List from "list"

let a = [1, 2]
let b = List.reverse(a)

print(a)
print(b)
```
2. Run `grain test.gr`

## Expected behavior

```
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ grain first.gr
Error: unrecognized flag --experimental-wasm-bigint
Try --help for options
[1, 2]
[2, 1]
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ 
```

## Actual behavior

```
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ grain first.gr
Error: unrecognized flag --experimental-wasm-bigint
Try --help for options
[1, 2]
[, , 1]
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ 
```

## Platform Information

Ubuntu 20.04
```
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ grain --version
Error: unrecognized flag --experimental-wasm-bigint
Try --help for options
Grain cli 0.4.2
Grain compiler 0.4.1
ashwin@ashwin-VirtualBox:~/Desktop/Grain (Test)$ 
```

**Comment by cician** [comment]
I can reproduce on grain compiled from latest git. The problem appears to be the linked to list spread syntax, not just List.reverse.

**Comment by cician** [comment]
Correcting myself. As mentioned on discord, the issue is in printing lists, not the list spread syntax. It's some kind of memory issue because calling ```print(a)``` affects ```print(b)```.
