### ISSUE TITLE
Repeated calls to Exception.printException print corrupted text

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#906]
This program
```grain
import Exception from "runtime/exception"

exception InvalidJSON(String)

Exception.printException(InvalidJSON("Infinity is not allowed in JSONNumber"))
Exception.printException(InvalidJSON("Infinity is not allowed in JSONNumber"))
Exception.printException(InvalidJSON("Infinity is not allowed in JSONNumber"))

print("end")
```

prints
```
InvalidJSON("Infinity is not allowed in JSONNumber")
        ��
        ��
end
```

instead of
```
InvalidJSON("Infinity is not allowed in JSONNumber")
InvalidJSON("Infinity is not allowed in JSONNumber")
InvalidJSON("Infinity is not allowed in JSONNumber")
end
```

**Comment by ospencer** [comment]
Hey @cician, this is expected since `printException` isn't meant to be called by user code, just the compiler when an uncaught exception is thrown. (The program will print the exception and then immediately exit.)

To print an exception in user code, regular `print` should work fine 🙂

**Comment by cician** [comment]
OK. So it's just silly me, calling random functions from the runtime without knowing what they do. I was using it in a test program hoping it would print a stack trace from an Exception object.

I'm closing the issue, but maybe this could serve as a use case for what can happens when others like me, use and abuse all exported functions from stdlib.
