### ISSUE TITLE
Infinite loop inside malloc.free

### ISSUE THREAD

**Issue by cician** [grain-lang/grain#927]
The below program causes an infinite loop inside `malloc.free`. It finishes without issues if executed with `--no-gc`.

I tried to narrow it down further, but gave up. Slight changes like the following make it **not** hang anymore:
- Changing the chars to simple ASCII values like 'a' and 'b'.
- Moving the if statement to the end of the loop.
- Changing the loop to `while(true)` or `for(;;)`.
- Not calling `Char.code`. Though I doubt it's got much to do with Char.code function itself, even if it's not fully conformant with the new convention for manual memory management.

``` grain
import Char from "char"

let chars = [> '\u{1F3F4}', '\u{E0067}' ]
let mut charPosition = 0
let len = 2
let mut done = false

while (!done) {
	if (charPosition >= len) {
		break
	}
	
	Char.code(chars[charPosition])
	charPosition = charPosition + 1
}
```

**Comment by ospencer** [comment]
Thanks @cician for the report! It was actually Char.code—premature free. 😩
