### ISSUE TITLE
List.filter doesn't return the expected list

### ISSUE THREAD

**Issue by k33g** [grain-lang/grain#936]
Hello,

- I want to filter `let food = ["🥖", "🥬", "🍅", "🧅", "🍖"]` with this predicate `(item) => item != "🧅"`
- the expected result is `["🥖", "🥬", "🍅", "🍖"]`
- the result provided by `List.filter` is `[, , "🥬", "🍅", "🍖"] ` (2 empty values) 

> source code
```grain
import String from "string"
import List from "list"

let food = ["🥖", "🥬", "🍅", "🧅", "🍖"]

let noOnion = (item) => item != "🧅"

let prep = List.filter(noOnion, food)

print(food) // ["🥖", "🥬", "🍅", "🧅", "🍖"]
print(prep) // [, , "🥬", "🍅", "🍖"] instead of ["🥖", "🥬", "🍅", "🍖"]
```

**Comment by peblair** [comment]
Hello @k33g! I believe this issue is the same as #892 . We've fixed it, but unfortunately have not yet cut the patch release with the fix. Is it possible for you to work from `main` in the meantime (I just tried this program out on my local build, and it works as expected)?

**Comment by k33g** [comment]
👋 @peblair oh yes I didn't see #892 but I confirm that I have the same issue with `reject`

I will see if I manage to build **Grain** from the `main` branch 😃

**Comment by peblair** [comment]
Perfect! The documentation is [here](https://grain-lang.org/docs/getting_grain#Building-Grain-from-Source), in case you need it. Let me know if you're still having issues or if this is good to close!

**Comment by k33g** [comment]
@peblair 👍 it works 😃 
I imported it in GitLab and build it inside GitPod 
now I'm trying to build a release from a fork on GitHub (but I almost never used GitHub actions 🤞)

**Comment by k33g** [comment]
the compiler is a lot faster 🚀

**Comment by phated** [comment]
> the compiler is a lot faster

Yep! Building from source produces a native compiler, opposed to the packaged compiler which is all running in JS 🙈
