### ISSUE TITLE
Investigate runtime/string compiling in runtime mode

### ISSUE THREAD

**Issue by phated** [grain-lang/grain#980]
Currently, our `runtime/string` module compiles in "normal mode" but with the `--no-pervasives` flag. I was discussing this with @ospencer and he believes this module might be refactored to run in "runtime mode" in order to remove the `--no-pervasives` flag requirement.

This is the only place we use `--no-pervasives`, so removing it could open up some refactoring opportunities.

**Comment by ospencer** [comment]
Since we got `@unsafe`, the `--no-pervasives` flag is a lot more attractive since it makes it a lot easier to write code for the runtime and we now have 7 modules that use it. @phated may I close this?

**Comment by phated** [comment]
Sounds like it!
