### ISSUE TITLE
Stdlib: Avoid double iteration on String.trim

### ISSUE THREAD

**Issue by ospencer** [grain-lang/grain#982]
There are some heuristics we can use to improve performance. See this discussion: https://github.com/grain-lang/grain/pull/951#discussion_r721777742

**Comment by phated** [comment]
Updated the title because the discussion in #951 points out that `trimStart` and `trimEnd` are both called upon the string which causes two iterations. This is different that #1442 which only uses low-level instructions to operate on bytes, but it still does two iterations.

**Comment by spotandjake** [comment]
I could be mistaken but the only logical way I see to use one iteration on `trimString` is to check each side of the string in one loop, This would likely create a bunch of code duplication though and wouldn't greatly reduce the number of instructions. I could be wrong though.

**Comment by spotandjake** [comment]
Thinking over this a bit more. I dont think the optimal solution is to use one loop. I think it would make sense to have the `trimString` function just return the byteIndex of the slice locations. and then we can do a single `newString` allocation after, and single `Memory.copy`.
